### PR TITLE
LOG4J2-1488 Add support for period in ISO8601 format

### PR DESCRIPTION
**Pull request by rzschech**
Add support for period in ISO8601 format as per the documentation: "millisecond separator may be either a comma ',' or a period '.'"

Also Java's `java.time.Instant.toString()` and JavaScript's `new Date().toISOString()` use '.' as well.

### CODE REVIEW

**Comment by garydgregory** [comment]
How about a unit tests? ;-)

**Comment by remkop** [comment]
PR looks good at first glance. Unit test would be nice. 

Can you link this pull request to another Jira? 
LOG4J2-1341 is the ticket for GC-free pattern converters which is not related to FixedDateFormat. Feel free to create a new Jira ticket if no matching one exists.

**Comment by rzschech** [comment]
This change is related to GC-free patterns as it allows DatePatternConverter to support a period in the ISO8601 format. Without this change the DatePatterConverter successfully formats using "yyyy-MM-dd'T'HH:mm:ss.SSS" but it doesn't do it using the GC-free FixedDateFormat.

If you wish though I can create a more specific Jira.

**Comment by rzschech** [comment]
Opps didn't mean to "Comment and close"

**Comment by remkop** [comment]
If you don't mind, more specific Jira tickets would be good: in our release notes we always include a detailed breakdown of what was changed and separate Jiras help with that.

**Comment by rzschech** [comment]
I've created a Jira, added a unit test and updated the pull request.

**Pull request closed without merging**
