### PR TITLE
LOG4J2-2885 Add support for US-style date patterns and micro/nano seconds to FixedDateFormat

### PR DESCRIPTION
**Pull request by sman-81**

### CODE REVIEW

**Review by rgoers — APPROVED** [review]
This looks good to me.

**Comment by sman-81** [comment]
How will you proceed with my PR?

**Comment by vy** [comment]
Thanks so much for the PR @sman-81! I have ported this to `master` as well.

**Comment by carterkozak** [comment]
@vy I think this broke builds on release-2.x for the same reason the PR build is failing, revapi needs the enum ordinal changes to be acknowledged.

**Comment by vy** [comment]
:man_facepalming: @carterkozak, right, thanks for the warning, fixed.

**Comment by sman-81** [comment]
Hi @carterkozak, hi @vy,
thank you both for fixing the **reviapi** build failure.
I should have spotted this myself. I must admit I've rarely built the whole project as it takes long (log4j-core ~ 15 minutes) and I assumed the suite was never green - but it actually is 👍

**Pull request merged**
