### PR TITLE
[LOG4J2-2919] Call ReliabilityStrategy's beforeStopAppenders() method before stopping AsyncAppender

### PR DESCRIPTION
**Pull request by gengyuanzhe**
Call ReliabilityStrategy's beforeStopAppenders() method before stopping AsyncAppender
to avoid errors caused by logging with AsyncAppender  while system is reconfiguring
Submitted by: gengyuanzhe <gengyuanzhe@gmail.com>

### CODE REVIEW

**Comment by gengyuanzhe** [comment]
@rgoers  Can you help me review my pr?

**Comment by jvz** [comment]
Right, those test failures are caused by a commit I made yesterday or two days ago that I need to revert (haven't had a chance to do so yet). As long as your PR isn't introducing new failures, you won't need to worry about the build failures.

**Comment by gengyuanzhe** [comment]
@jvz  Truly appreciate your reply. I'm newer for this project. I wonder what should I do next for this PR or issue?

**Comment by jvz** [comment]
If you're able to write a unit test that would fail without your PR and passes with your PR, that would help a lot in preventing regressions. Otherwise, one or more of the committers here will review and merge this.

There's been a bit of work recently in our unit tests (hence the test failures at the moment) which might make it easier to write a test for. You could use Mockito or some stub appenders to verify the behavior. Let me know if you have any questions about the testing framework as our Log4j-specific code (the JUnit 5 parts at least) are all relatively new still.

**Comment by gengyuanzhe** [comment]
@jvz This PR is about a concurrent problem. As we all know, concurrency problems always require some kind of execution order.  I cannot write a standard unit test for this case.  But  by modifying the method `org.apache.logging.log4j.core.appender.AsyncAppender#append` and add a `sleep()` in the beginning, I can control the excution order and  reproduce the error in a unusual way.  I've describe the details in my [issue](https://issues.apache.org/jira/browse/LOG4J2-2919). If you have some advices to **write a standard unit test for my problem**, please tell me. (I try to learn how to test this case from  [LOG4J2-1121](https://issues.apache.org/jira/browse/LOG4J2-1121), which first introduce `ReliabilityStrategy` but miss handling the AsyncAppender case, but there are also no unit tests for the LOG4J2-1121).

**Comment by jvz** [comment]
I usually use https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CountDownLatch.html for chaining together asynchronous things (particularly in unit tests) where you can await the latch where you'd normally sleep, and countdown the latch in places where work is completed. However, since concurrency bugs like that are difficult to test sometimes, I think it'd also be acceptable if you include the detailed reproduction steps in the Jira ticket so that I can try writing one. I may be able to help you design a unit test here, though, depending on how comfortable you are with concurrency code.

**Comment by gengyuanzhe** [comment]
@jvz I have described the reproduction step in great detail in [LOG4J2-2919 of Jira](https://issues.apache.org/jira/browse/LOG4J2-2919), and draw a picture to illustrate the 2 thread excute order, as well as the test code and log4j2.properties
Need I copy it to LOG4J2-1121?

**Comment by jvz** [comment]
Just the one Jira is fine, thanks!

**Comment by gengyuanzhe** [comment]
> Just the one Jira is fine, thanks!

Ok, it seems that you just open my Jira link a minute ago :joy:. Any way, it's a big step forward. If you have question about my reproduction steps, please tell me. And please help me finish the unit test. Thank you~

**Comment by jvz** [comment]
Ooh yeah, this is going to be an interesting test to write. This will likely require some test-specific refactoring. Let me see if I can figure this out! :)

**Comment by jvz** [comment]
Turns out this didn't really need any concurrency primitives as I found an appropriate extension point to assert behavior upon.

**Review by jvz — APPROVED** [review]

**Pull request merged**
