### PR TITLE
Support for disruptor-4.0.0

### LINKED ISSUE #1829: Support for com.lmax:disruptor:4
## Description

When I run with async logger and `com.lmax:disruptor:4`, I get the following error:

> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: com/lmax/disruptor/SequenceReportingEventHandler
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
> 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor.start(AsyncLoggerConfigDisruptor.java:226)
> 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:312)
> 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
> 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
> 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
> 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
> 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
> 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
> 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
> 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
> 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
> 	... 1 more
> Caused by: java.lang.ClassNotFoundException: com.lmax.disruptor.SequenceReportingEventHandler
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
> 	... 21 more
> ```

## Configuration

```json
{
  "Configuration": {
    "Appenders": {
      "Console": {
        "name": "Console-Appender",
        "target": "SYSTEM_ERR",
        "PatternLayout": {
          "pattern": "%d{DEFAULT} [%level] - %msg%n"
        }
      },
      "Async": {
        "name": "Async-Console-Appender",
        "AppenderRef": {
          "ref": "Console-Appender"
        },
        "LinkedTransferQueue": {}
      }
    },
    "Loggers": {
      "AsyncRoot": {
        "level": "INFO",
        "AppenderRef": {
          "ref": "Async-Console-Appender"
        }
      }
    }
  }
}
```

**Version:** 2.20.0
**Operating system:** MacOS 13.6
**JDK:** OpenJDK 21

## Reproduction

Just run an Java class with the following static field:

```java
private static final Logger LOGGER = LogManager.getLogger();
```

### PR DESCRIPTION
**Pull request by Dreeam-qwq**
Add support for disruptor 4.0.0 to close [LOG4J2-3595](https://issues.apache.org/jira/browse/LOG4J2-3595) (#1829). Tested and looks good.

### CODE REVIEW

**Comment by ppkarwasz** [comment]
@Dreeam-qwq,

All 2.x releases must run on JDK 8. Since Disruptor 4.x requires a Java 11 runtime, we can not drop support for Disruptor 3.x.

Looking at your patch, the only breaking change that occurred is the disappearance of the `SequenceReportingEventHandler` and `LifecycleAware` interfaces, so you can work around these restrictions by:
 - restoring version `3.4.4` in the POM file,
 - removing the `@Override` annotations from the new `EventHandler` methods,
 - create a `RingBufferLogEventHandler3` and `AsyncLoggerConfigDisruptor#Log4jEventWrapperHandler3` classes that extend their v4 counterparts and differ just in the `implements` clause:
    ```java
    public class RingBufferLogEventHandler3 extends RingBufferLogEventHandler
        implements SequenceReportingEventHandler<RingBufferLogEvent>, LifecycleAware  {}
     ```
 - add logic to switch between `RingBufferLogEventHandler3` and `RingBufferLogEventHandler` based on the existence of the `SequenceReportingEventHandler` interface.
 - add some logic to switch between our `TimeoutBlockingWaitStrategy` and the one shipped with Disruptor 4.x.
 
 To test the PR run:
 ```
 ./mvnw install -pl log4j-core
 ```
 followed by:
 ```
 ./mvnw verify -Pjava8-tests -Dtest="org/apache/logging/log4j/core/async/*"
 ```
 to test on JDK 8 (you need a Maven toolchains configuration) and Disruptor 3.x and
 ```
  ./mvnw verify -Dtest="org/apache/logging/log4j/core/async/*" -Ddisruptor.version=4.0.0
  ```
  to test on JDK 11 and Disruptor 4.x.

**Comment by ppkarwasz** [comment]
Closes #1829 .

**Comment by Dreeam-qwq** [comment]
I'm sorry that I have no enough time to do this recently, I'll close this pr, sorry to waste your time to review it, also thanks for you to give explanation to me.

**Comment by ppkarwasz** [comment]
@Dreeam-qwq,

Take your time. We won't be able to include this PR into `2.21.0` anyway, since the release process is already in motion.

You can also resubmit this PR against the `main` branch, which is based on Java 11, so most of the problems disappear.

**Pull request closed without merging**
