### PR TITLE
 LOG4J2-2978: add support for Jakarta EE 9

### PR DESCRIPTION
**Pull request by mseele**

### CODE REVIEW

**Review by rgoers — APPROVED** [review]
Thanks for doing this!  We will need to include some documentation changes too for this.

**Review by rgoers — APPROVED** [review]
Thanks. This looks great! I will get this merged as soon as I get a few minutes to also do the cherry-pick to master.

**Comment by rgoers** [comment]
This PR fails to build. It is referencing hamcrest-all. I believe release-2.x was modified to use the hamcrest dependency instead.

**Comment by mseele** [comment]
> This PR fails to build. It is referencing hamcrest-all. I believe release-2.x was modified to use the hamcrest dependency instead.

@rgoers I've fixed that problem. Everything should be fine, again.

**Pull request merged**
