### PR TITLE
LOG4J-2635: Fix java.version check in ThreadNameCachingStrategy

### PR DESCRIPTION
**Pull request by fgunbin**

### CODE REVIEW

**Comment by fgunbin** [comment]
@garydgregory No problem, though I viewed duplication in test file as a kind of test that strings are right.
Add to org.apache.logging.log4j.core.util.Constants, right?

**Comment by remkop** [comment]
@fgunbin if these are only locally used I would prefer not to define them in `Constants` but just define them locally.

**Comment by carterkozak** [comment]
I think we can use the enum `name()` from `ThreadNameCachingStrategy` instead of defining new constants.

**Comment by remkop** [comment]
Makes sense.

**Comment by fgunbin** [comment]
Pushed the update, please check.  
There's Travis failure somewhere in Log4j Sample Configuration Service build, and I cannot see the reason, could you help please?

**Pull request merged**
