### PR TITLE
Simplify site generation

### PR DESCRIPTION
**Pull request by vy**
**Warning! These changes are based on the work delivered in #1145 replacing the `maven-changes-plugin`. Hence, that PR needs to be merged first!**

This PR attempts to simplify the site generation.
Highlights from the changes are as follows:

1. all Maven reporting is disabled
1. Coveralls, JaCoCo, DOAP, PDF configurations are removed
1. `enforce-upper-bound-deps` Maven enforcer rule is fixed
1. `/pom.xml` is overhauled (`developers` are simplified, `contributors` are removed, unused configurations/properties are removed, etc.)
1. `maven-site-plugin` is disabled for all modules except `/pom.xml`
1. all `<module>/src/site/markdown/index.md[.vm]` files are moved to `/src/site/markdown/<module>.md[.vm]`
1. build instructions are updated

As a result, **`./mvnw site` takes less than 30s on a decent laptop.**

### CODE REVIEW

**Comment by rgoers** [comment]
I pulled logging-log4j-tools and built it. I ran mvn clean install (which worked). I then ran mvn site, which failed with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.12.0:site (default-site) on project log4j: SiteToolException: The site descriptor cannot be resolved from the repository: ArtifactResolutionException: Unable to locate site descriptor: Could not transfer artifact org.apache.logging:logging-parent:xml:site_en:7 from/to spring-snapshots (https://repo.spring.io/libs-snapshot-local): Failed to transfer file https://repo.spring.io/libs-snapshot-local/org/apache/logging/logging-parent/7/logging-parent-7-site_en.xml with status code 409
[ERROR]   org.apache.logging:logging-parent:xml:7
```

**Comment by vy** [comment]
@rgoers, it simply works on my machine. Since `logging-log4j-tools` release is stuck on INFRA-23996, I cannot prove my claim in CI, i.e., GitHub Actions.

Would you mind trying `./mvnw clean site` in `mvn-site-simplified` branch, please?

Which module fails to build? `log4j-spring-cloud-config-sample-server`?

**Comment by rgoers** [comment]
It fails at the root of the project. It isn't in any module.

**Comment by ppkarwasz** [comment]
@rgoers: my guess is that you are using a Maven Central mirror that does not contain the `logging-parent.site.*` artifacts?

**Comment by rgoers** [comment]
It turns out I had some Spring repos in my settings.xml from when I was adding out stuff to Spring and that messed it up. After removing it the site built fine and only took 47 seconds!

**Comment by rgoers** [comment]
Under components, when I select "Implementation" I get a file not found. All the other pages are fine.

**Review by ppkarwasz — APPROVED** [review]

**Comment by vy** [comment]
> Under components, when I select "Implementation" I get a file not found. All the other pages are fine.

I have removed that page, since it was empty anyway. Now, in c6125223, removed it from the menu too.

> Note - make sure you do `mvn site:stage -DstagingDirectory=$HOME/log4j` to generate the full web site.

:heavy_check_mark:

**Pull request merged**
