### PR TITLE
LOG4J2-2656: Add support of ignoreKafkaConnectionError flag

### PR DESCRIPTION
**Pull request by akrikheli**
See https://issues.apache.org/jira/browse/LOG4J2-2656

### CODE REVIEW

**Comment by rgoers** [comment]
I am continuing to think about this as I am not sure if this is the right way to fix the problem.

**Comment by carterkozak** [comment]
It feels a bit odd for the Kafka appender to work differently from other appenders when creation fails. I wonder if it would be better if we provided an appender wrapper (similar to failover appender) which can create appenders lazily and log the failure without stopping the application? Such an appender could apply to any existing appender, and wouldn't require special boolean flags in each implementation.

**Comment by rgoers** [comment]
@carterkozak The AppenderControl already wraps Appenders to catch the exceptions they throw. There is already a generic way to cause it to stop suppressing the exceptions that are thrown while it is executing. But off the top of my head I don't recall if there is a standard way to handle exceptions while the Appender is created. Most of the ones I have seen just the Appender to be null, but other stuff still may succeed.

**Comment by carterkozak** [comment]
A workaround might be to use a RoutingAppender with a single default route of the KafkaAppender defined in place. That should lazily attempt to create the delgate KafkaAppender, logging failures and continuing.

**Pull request closed without merging**
