### PR TITLE
Remove `log4j-kubernetes` in version 3.x

### PR DESCRIPTION
**Pull request by ppkarwasz**
Due to differences in the lifecycle of Log4j Core and Kubernetes Client, we remove `log4j-kubernetes` from the 3.x release and redirect users to Fabric8's own `kubernetes-log4j` artifact introduced in [version 6.11.0](https://github.com/fabric8io/kubernetes-client/discussions/5834).

## Motivation

The `log4j-kubernetes` lookup depends on:

* the very stable `StrLookup` interface from Log4j Core,
* the evolving set of Kubernetes metadata provided by Kubernetes Client.

Therefore it makes more sense to distribute the lookup together with Kubernetes Client.

### CODE REVIEW

**Review by rgoers — APPROVED** [review]
This looks good to me. Should it be dropped in 2.x as well?

**Comment by ppkarwasz** [comment]
> This looks good to me. Should it be dropped in 2.x as well?

I guess we can also drop it from 2.x.

**Comment by vy** [comment]
+1 for dropping it from `2.x`. @ppkarwasz, could you also submit a PR for that too, please?

**Comment by ppkarwasz** [comment]
@vy, I submitted a 2.x equivalent in #2412

**Comment by ppkarwasz** [comment]
Closes #2218

**Pull request merged**
