### PR TITLE
[LOG4J2-1923] Allow having the stacktrace as a string in JSONLayout, XMLLayout and YAMLLayout

### PR DESCRIPTION
**Pull request by imriz**

### CODE REVIEW

**Comment by mikaelstaldal** [comment]
Can you file an JIRA issue about this here: https://issues.apache.org/jira/browse/LOG4J2/

and mention the JIRA issue here?

It would be good with some motivation why this would be a good idea, such as example use case.

**Comment by imriz** [comment]
@mikaelstaldal I've opened the JIRA: LOG4J2-1923

**Comment by mikaelstaldal** [comment]
It would be nice to have the same functionality in XmlLayout and YamlLayout. It should be easy to add that since they use the same Jackson based framework.

**Comment by imriz** [comment]
Sure. I will check if I can extend it to xml and yaml.

**Comment by mikaelstaldal** [comment]
Documentation in `layouts.xml.vm` should be updated.

**Comment by imriz** [comment]
@mikaelstaldal Hi :) I've extended this to YAML and XML + updated `layouts.xml.vm`

**Comment by mikaelstaldal** [comment]
To avoid breaking binary compatibility, we should not modify public/protected constructors/methods of JsonLayout, XmlLayout, YamlLayout. Add the new flag to the Builder only.

**Comment by mikaelstaldal** [comment]
It would be nice to unit test this new feature for XmlLayout and YamlLayout also.

**Pull request closed without merging**
