### PR TITLE
Log4j 1.2 bridge throws `ClassCastException` when using `SimpleLayout` and others

### PR DESCRIPTION
**Pull request by ppkarwasz**
Since not all Log4j 1.x component builders extend `AbstractBuilder`, `BuilderManager#createBuilder` throws a `ClassCastException` when instantiating some of them.

For example using a `SimpleLayout` in `log4j.properties` file fails.

This PR fixes some test from #706 .

### CODE REVIEW

**Comment by garydgregory** [comment]
"Since not all Log4j 1.x component builders extend AbstractBuilder, BuilderManager#createBuilder throws a ClassCastException when instantiating some of them."

@rgoers Your thoughts: Is this an omission or by design? Should all builders extend or do we indeed need to introduce this interface?

**Comment by garydgregory** [comment]
@ppkarwasz 
Please rebase on git branch `release-2.x`.

**Comment by ppkarwasz** [comment]
@garydgregory,
I rebase the PR and added some licenses to the XML config files.

**Comment by garydgregory** [comment]
@ppkarwasz 
Thank you for your work on this PR! 👍 :-) I brought in this PR directly as a diff with these changes:
- Add the Apache license header to XML test fixtures.
- Remove unused imports.
- Add missing spaces in Java source.
- Remove some whitespace.

**Comment by ppkarwasz** [comment]
@garydgregory, I don't see these changes on the `release-2.x` branch. The main point of this PR is to exchange the lower bound `AbstractBuilder` in the signature:

`private <T extends AbstractBuilder> T createBuilder(PluginType<?> plugin, String prefix, Properties props)`

with something all builders extend. Introducing a `Builder` interface from which `LayoutBuilder` and company inherit seemed like an elegant solution, although removing the lower bound altogether should also work.

**Comment by garydgregory** [comment]
@ppkarwasz 
Oops, I messed up by closing this PR, so sorry, would you mind rebasing on `release-2.x`?

**Comment by ppkarwasz** [comment]
@garydgregory,

I rebased the PR and added a failsafe to `BuilderManager#createBuilder`: if a builder does not implement any of the `*Builder` interfaces a warning is logged instead of a `ClassCastException`.

**Pull request merged**
