### PR TITLE
Adds xmlns in schema and some tags

### PR DESCRIPTION
**Pull request by shubhankar1100**
Adds xmlns in schema and adds elements like Appender, console, PatternLayout and remove  mandatory elements type from Properties and ThresholdFilters as they are not mandatory always.

### CODE REVIEW

**Comment by shubhankar1100** [comment]
Hi, 

Can anyone review this patch?

**Comment by garydgregory** [comment]
Did you do a full build with this patch like "mvn clean install" ?

**Comment by garydgregory** [comment]
In Git master. Local build OK with 'mvn clean install'. This will be in out upcoming 2.8 release.

Thank you for your contribution. Keep them coming! :-)

**Comment by shubhankar1100** [comment]
Yes, I only did "mvn install" not maven clean install

**Pull request closed without merging**
