### PR TITLE
Refactored data clumps with the help of LLMs (research project)

### PR DESCRIPTION
**Pull request by compf**
Hello maintainers,

I am conducting a master thesis project focused on enhancing code quality through automated refactoring of data clumps, assisted by Large Language Models (LLMs).

<details>
  <summary>Data clump definition</summary>
  
A data clump exists if
1. two methods (in the same or in different classes) have at least 3 common parameters and one of those methods does not override the other,  or 
2. At least three fields in a class are common with the parameters of a method (in the same or in a different class), or
3. Two different classes have at least three common fields
  
See also the following UML diagram as an example
Example data clump
</details>

I believe these refactoring can contribute to the project by reducing complexity and enhancing readability of your source code.

Pursuant to the EU AI Act, I fully disclose the use of LLMs in generating these refactorings, emphasizing that all changes have undergone human review for quality assurance. 

Even if you decide not to integrate my changes to your codebase (which is perfectly fine), I ask you to fill out a feedback survey, which will be scientifically evaluated to determine the acceptance of AI-supported refactorings. You can find the feedback survey under https://campus.lamapoll.de/Data-clump-refactoring/en

Thank you for considering my contribution. I look forward to your feedback. If you have any other questions or comments, feel free to write a comment, or email me under tschoemaker@uni-osnabrueck.de .

Best regards,
Timo Schoemaker
Department of Computer Science
University of Osnabrück

### CODE REVIEW

**Review by garydgregory — COMMENTED** [review]
-1 as it stands for the simple reason that the new public code has ZERO Javadoc and should have its own tests. It is also unlikely that we should or are allowed to accept AI generated code since the provenance is not Apache licensed, it might even be a copyright violation, who knows... also this looks like refactoring for its own sake...

**Comment by compf** [comment]
Thank you very much the feedback :)

**Comment by ppkarwasz** [comment]
@compf,

I agree with Gary: the refactoring itself doesn't have much value.

It would be however interesting to know:

- why your LLM specifically found this data clump. The group of parameters `Level, Marker, Throwable, String` that starts from `Logger` seems easier to spot.
- did you architecture your model to take into account breaking API changes? I noticed that your refactoring only refactors `private` methods.
- did you publish your model somewhere on Github?

**Comment by compf** [comment]
> @compf,
> 
> I agree with Gary: the refactoring itself doesn't have much value.
> 
> It would be however interesting to know:
> 
>     * why your LLM specifically found this data clump. The group of parameters `Level, Marker, Throwable, String` that starts from `Logger` seems easier to spot.
> 
>     * did you architecture your model to take into account breaking API changes? I noticed that your refactoring only refactors `private` methods.
> 
>     * did you publish your model somewhere on Github?

Thank you also for the feedback: About your questions

1 and 2) The LLM chooses the data clumps based on many information. Particularly how many method parameters/ fields are part of the data clump, how often it is repeated in a single file or  in how in many files. Also as you noted the fact that the public interface should not be refactored is important. Since LLMs are blackboxes I cannot say why it has chosen this data clump. However, all this information is  considered, and then there is some manual review by me whether the refactoring would be difficult to achieve. So your Logger example is an important part of the Core API and would never be refactored unless someone really wants to do this :)

3) I am not training my own LLM. I am using GPT4-1106 from OpenAI. If you mean my source code, you can find it in my GitHub repo (data_clump_solver), but it still in a WIP state and I am continuously using your feedback to improve it if the chosen architecture allows it easily :)

**Comment by garydgregory** [comment]
> I am not training my own LLM. I am using GPT4-1106 from OpenAI

That's the basic problem here: You do not know if the end result contains a copy of code under a license that is not allowed in Apache projects.

Using a model that trains on open source code would solve that issue for you.

**Comment by compf** [comment]
> > I am not training my own LLM. I am using GPT4-1106 from OpenAI
> 
> That's the basic problem here: You do not know if the end result contains a copy of code under a license that is not allowed in Apache projects.
> 
> Using a model that trains on open source code would solve that issue for you.

That's a fair point, but I think this would be more relevant if the LLM improved an algorithm or otherwise improve the functionality of software. Such simple refactoring, as was done here, is not very creative and could have been performed by a human or an automated tool.
 Nevertheless, I fully agree that one should be absolutely transparent about the use of LLMs and I can understand that this can be a reason to reject such pull requests

**Comment by vy** [comment]
@compf, I am closing this issue due to shared concerns by maintainers. Feel free to re-submit it with requested changes.

**Pull request closed without merging**
