### PR TITLE
Mongodb2 test rule I/O isolated to the target directory

### PR DESCRIPTION
**Pull request by cakofony**
Access to user home directory may cause test flakes.

### CODE REVIEW

**Comment by jvz** [comment]
Does this help fix the jenkins/travis build problem? I'm not exactly sure if it's building with the new settings or not here.

**Comment by jvz** [comment]
From what I've seen, you'll want to mess around with the `~/.embedmongo` directory that gets created.

**Comment by garydgregory** [comment]
The painful part about putting anything in the target folder is that it gets deleted on each build. Downloading Mongo on each build is something we want to avoid IMO. I think we just need to make the user folder work...

**Comment by cakofony** [comment]
Makes sense, closing this one out for now. Will come back to the flake when I have a moment.

**Pull request closed without merging**
