### PR TITLE
[LOG4J2-3040][2.x] Avoid ClassCastException in JeroMqManager with custom LoggerContextFactory

### PR DESCRIPTION
**Pull request by grgrzybek**
Signed-off-by: Grzegorz Grzybek <gr.grzybek@gmail.com>

### CODE REVIEW

**Comment by garydgregory** [comment]
@grgrzybek 
Why are there 2 PRs with the same title? Please pick one.

**Comment by grgrzybek** [comment]
@garydgregory one is for `release-2.x` branch and one for `master` branch (I've renamed them).

**Comment by garydgregory** [comment]
@grgrzybek 
Please rebase on master to pick up the build fix.

**Comment by grgrzybek** [comment]
hmm, this pr (#791) is for 2.x, so I don't think I should rebase. and I see #790 is already up to date...

**Comment by ppkarwasz** [comment]
@grgrzybek: Gary surely meant rebase upon `release-2.x` so that the build does not fail.

**Comment by grgrzybek** [comment]
got it, rebased and `-f push`dd

**Comment by garydgregory** [comment]
> @grgrzybek: Gary surely meant rebase upon `release-2.x` so that the build does not fail.

Yes, thank you!

**Comment by garydgregory** [comment]
> @garydgregory one is for `release-2.x` branch and one for `master` branch (I've renamed them).

TY @grgrzybek !

**Pull request merged**
