### PR TITLE
Add mention of "CVE creation process" to the security page.

### PR DESCRIPTION
**Pull request by vy**
Removed statements that don't apply anymore.

### CODE REVIEW

**Review by jvz — APPROVED** [review]
Looks good. Could potentially note that the vote happens on the security list or something.

**Comment by vy** [comment]
> Looks good. Could potentially note that the vote happens on the security list or something.

Good point @jvz! Done.

**Comment by jvz** [comment]
Do we need a cherry pick to master as well?

**Comment by vy** [comment]
Really sharp of you @jvz! :hocho: Done.

**Pull request merged**
