### PR TITLE
Upgrade LMAX Disruptor to version 4.0.0

### PR DESCRIPTION
**Pull request by tomerarazy**

### CODE REVIEW

**Comment by vy** [comment]
@tomerarazy, I don't think this will work. See #1829 and [LOG4J2-3595](https://issues.apache.org/jira/browse/LOG4J2-3595). We would appreciate it if you can submit a PR fixing the issue via the way described in LOG4J2-3595.

**Comment by tomerarazy** [comment]
> @tomerarazy, I don't think this will work. See #1829 and [LOG4J2-3595](https://issues.apache.org/jira/browse/LOG4J2-3595). We would appreciate it if you can submit a PR fixing the issue via the way described in [LOG4J2-3595](https://issues.apache.org/jira/browse/LOG4J2-3595).

If I understand the issue is backward compatibility with older Java versions, I don't mind taking a shot at this but I'm not familiar with the log4j (other than as a user) so I don't even know where to start looking on how different Java versions affect which code we're loading, can you please provide some pointers to where I can start looking?

**Comment by ppkarwasz** [comment]
I would prefer to use the trick I described in #1856.

In Disruptor 4.x two things changed:

- `EventHandler` has new default methods that come from its previous sub-interfaces,
- some sub-interfaces of `EventHandler` disappeared.

We can easily work with this, so that:

- our code compiles with Disruptor 3.x,
- users can use both Disruptor 3.x and Disruptor 4.x at runtime.

The details are in #1856.

**Comment by jvz** [comment]
I'm going to go ahead and apply this idea to main since that has a baseline requirement of Java 11 already.

**Comment by jvz** [comment]
Straightforward approach in main: https://github.com/apache/logging-log4j2/commit/9dcb10bf300432b353cb793a81d1202bce36ef77

**Comment by tcmot** [comment]
Refer to this ticket.

https://github.com/LMAX-Exchange/disruptor/issues/467#issuecomment-1855643967

**Pull request closed without merging**
