### PR TITLE
Remove unnecessary threadlocal in MdcPatternConverter

### PR DESCRIPTION
**Pull request by cakofony**
We can write directly to the supplied StringBuilder.

### CODE REVIEW

**Comment by mikaelstaldal** [comment]
@remkop what do you think? You added this `ThreadLocal`.

**Comment by remkop** [comment]
The proposed change would result in a trailing comma after the last key-value pair. For that reason I would say no. 

If there is a way to avoid the temporary buffer without changing the behavior then that would be good. So I agree with the general sentiment but I don’t see how to accomplish it (yet).

In its current form we cannot accept the pull request.

**Comment by cakofony** [comment]
@remkop MdcPatternConverter.java:126 takes care of that case, I added additional testing to ensure it doesn't break moving forward either.

**Comment by remkop** [comment]
My bad, I missed that. :-/
Let me take another proper look.

**Comment by cakofony** [comment]
No worries, thanks!

**Comment by remkop** [comment]
Ok. Looks good. Tests all pass.

Ralph started the release earlier today so I don't want to interrupt that, but I'll push the merge when the release is done.

**Comment by remkop** [comment]
I created https://issues.apache.org/jira/browse/LOG4J2-2127 for this PR.

**Comment by remkop** [comment]
Fixed in master. Please verify and close the https://issues.apache.org/jira/browse/LOG4J2-2127 ticket.

Thanks for the PR! Keep 'em coming!

**Pull request merged**
