### PR TITLE
Avoid Locale-dependent lowercase/uppercase string conversion

### PR DESCRIPTION
**Pull request by aawad6**
As there're remaining locale-dependent calls of String#toLowerCase and String#toUpperCase. These calls are replaced with Strings#toRootLowerCase and Strings#toRootUpperCase.

Issue https://github.com/apache/logging-log4j2/issues/1281.

### CODE REVIEW

**Comment by vy** [comment]
@aawad6, mind giving us a heads up when you are done?

**Comment by aawad6** [comment]
I think that's all, I'm ready for a review.

**Comment by ppkarwasz** [comment]
@aawad6,

Sorry for the delay. The changes you did look good to me, but you missed some `toLowerCase/toUpperCase` calls, e.g. in `AnsiEscape` or `HighlightConverter`.

Could you replace all calls to `toLowerCase/toUpperCase` that take a constant locale parameter (e.g. `Locale.US` or `Locale.ENGLISH`)? If we remove most of the `String#toLowerCase` callsites it will be easier to check if someone didn't introduce new ones.

**Comment by garydgregory** [comment]
> @aawad6,
> 
> Sorry for the delay. The changes you did look good to me, but you missed some `toLowerCase/toUpperCase` calls, e.g. in `AnsiEscape` or `HighlightConverter`.
> 
> Could you replace all calls to `toLowerCase/toUpperCase` that take a constant locale parameter (e.g. `Locale.US` or `Locale.ENGLISH`)? If we remove most of the `String#toLowerCase` callsites it will be easier to check if someone didn't introduce new ones.

I took a deep dive into this a while back, see https://garygregory.wordpress.com/2015/11/03/java-lowercase-conver, and I think `Locale.ROOT` is what you want.

**Comment by aawad6** [comment]
@ppkarwasz 

I thought they should be untouchable as they are added by intention, nevertheless, I eliminated all the usage of constant Locale (e.g. `Locale.US` or `Locale.ENGLISH`) as you mentioned.

**Review by ppkarwasz — APPROVED** [review]
@aawad6, looks good to me.

@garydgregory, we apply exactly what you suggested in your blog: `Strings.toRootUpperCase/Strings.toRootLowerCase`.

**Pull request merged**
