### PR TITLE
run CI build for pull requests

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by jvz** [comment]
Is this PR only being built then because of the config update here?

BTW, our workflow is broken at the moment anyways. Hopefully we can figure it out soon, but something seems to have changed in the setup java action which isn't using the same environment variables anymore.

**Comment by jvz** [comment]
In the meantime, I've enabled Jenkins builds for PRs from collaborators at least.

**Comment by sullis** [comment]
> Is this PR only being built then because of the config update here?
> 

Yes.

**Comment by jvz** [comment]
I noticed one potential issue here which I'm not sure how to configure: PRs that are created from branches on origin (e.g., how Dependabot is configured) end up being built twice due to being pushed to a branch and a PR.

**Pull request merged**
