### PR TITLE
Migrate `log4j-jul` to JUnit 5

### PR DESCRIPTION
**Pull request by AlbaHerrerias**
Hello 👋

We are from Neighbourhoodie, the implementation partner of the STF Bug Resilience Program. This work is part of our agreed Milestone 1. Upgrade from JUnit 4 to JUnit 5. This PR migrates the tests located in `log4j-jul`.

Thank you!

## Checklist

* Base your changes on `2.x` branch if you are targeting Log4j 2; use `main` otherwise
* `./mvnw verify` succeeds (if it fails due to code formatting issues reported by Spotless, simply run `./mvnw spotless:apply` and retry)
* Non-trivial changes contain an entry file in the `src/changelog/.2.x.x` directory
* Tests for the changes are provided
* [Commits are signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (optional, but highly recommended)

### CODE REVIEW

**Comment by AlbaHerrerias** [comment]
Hi, we are currently blocked and would like your advice. We've found out that the `surefire-junit47` provider specified [here](https://github.com/apache/logging-log4j2/blob/031d4dab8b32e1d3802f73495a7bb36b8b2685f5/log4j-jul/pom.xml#L100) only executes JUnit 4 tests. We've attempted to change the version and the provider with no luck. Is there another version of this dependency that would set up java.util.logging as required, but will also run JUnit 5 tests? Do you have any pointers for us? Thank you

**Comment by ppkarwasz** [comment]
@AlbaHerrerias,

The problem with `surefire-junit-platform` was that either Surefire or JUnit 5 (I don't remember which one) initializes JUL (and therefore Log4j) way before control is transferred to the test class. Therefore this code executes too late:

https://github.com/apache/logging-log4j2/blob/031d4dab8b32e1d3802f73495a7bb36b8b2685f5/log4j-jul/src/test/java/org/apache/logging/log4j/jul/test/CoreLoggerTest.java#L59-L62

To workaround that, all the tests must be split into at least 4 Surefire runs, depending on the system properties that they need.
Most test classes require the `java.util.logging.manager` property to be set (except `Log4jBridgeHandlerTest`), but some need additional properties.
For example `AsyncLoggerThreadsTest` additionally needs the `log4j2.contextSelector` property to be set:

```xml
          <execution>
            <id>async-logger-test</id>
            <goals>
              <goal>test</goal>
            </goals>
            <phase>test</phase>
            <configuration>
              <includes>
                <include>**/AsyncLoggerThreadsTest.class</include>
              </includes>
              <!-- Use custom `j.u.l.LogManager` and an asynchronous selector -->
              <systemPropertyVariables>
                <java.util.logging.manager>org.apache.logging.jul.tolog4j.LogManager</java.util.logging.manager>
                <log4j2.contextSelector>org.apache.logging.log4j.core.async.AsyncLoggerContextSelector</log4j2.contextSelector>
              </systemPropertyVariables>
            </configuration>
          </execution>
```

`CoreLoggerTest` needs an additional `log4j2.julLoggerAdapter` system property.

**Comment by AlbaHerrerias** [comment]
Hello @ppkarwasz , thank you for your help, it unblocked me.

**Review by ppkarwasz — APPROVED** [review]
@AlbaHerrerias,

LGTM, thanks!

**Comment by AlbaHerrerias** [comment]
Hello @ppkarwasz. I wanted to ask if this refactor needs to be ported to `main`. Previously, your team has been handling the porting, and I was wondering if you plan to continue doing so for this and the other modules we've refactored that are not yet in `main`. Thank you! 🙏

**Comment by ppkarwasz** [comment]
> Previously, your team has been handling the porting, and I was wondering if you plan to continue doing so for this and the other modules we've refactored that are not yet in `main`. Thank you! 🙏

I have the impression that you did all the ports to `main` (of course for modules that still exist in main). The version of `log4j-jul` in `main` is strongly amputated, so no need to migrate this one.

**Comment by AlbaHerrerias** [comment]
@ppkarwasz 
They were made by @vy 🙇

I've compiled a small list with our changes:

| PR against `2.x` | Ported to `main` | 
| - | - | 
| [`log4j-jdbc-dbcp2`](https://github.com/apache/logging-log4j2/pull/3007) | [Yes, done by vy](https://github.com/apache/logging-log4j2/commit/1a8df6bbf6dc39109ad9320a0af66e5b308c5caa) | 
| [`log4j-jpl`](https://github.com/apache/logging-log4j2/pull/3029) | [Yes, done by vy](https://github.com/apache/logging-log4j2/commit/b6101b34b3d51f8bd4e9f4278a6287f06149e3f9) | 
| [`log4j-to-slf4j`](https://github.com/apache/logging-log4j2/pull/3040) | [No need](https://github.com/apache/logging-log4j2/pull/2924) |
| [`log4j-slf4j-impl`](https://github.com/apache/logging-log4j2/pull/3138)  | [No need](https://github.com/apache/logging-log4j2/pull/2924) | 
| [`log4j-slf4j2-impl`](https://github.com/apache/logging-log4j2/pull/3080)  | [No need](https://github.com/apache/logging-log4j2/pull/3080#pullrequestreview-2387694227) | 
| [`log4j-jul`](https://github.com/apache/logging-log4j2/pull/3225)| [No need](https://github.com/apache/logging-log4j2/pull/3225#issuecomment-2535938492) | 
| [`log4j-jpa`](https://github.com/apache/logging-log4j2/pull/3060) | Does not look it is in `main` |
| [`log4j-jakarta-smtp`](https://github.com/apache/logging-log4j2/pull/3052) | Does not look it is in `main` |
| [`log4j-taglib`](https://github.com/apache/logging-log4j2/pull/3227)  | Does not look it is in `main` | 
| [`log4j-1.2-api`](https://github.com/apache/logging-log4j2/pull/3067) | Does not look it is in `main`  | 
| [`log4j-api-test`](https://github.com/apache/logging-log4j2/pull/3218) (not finished, we need assistance) | Does not look it is in `main`  | 
| [`log4j-osgi-test`](https://github.com/apache/logging-log4j2/pull/3219) | | 
| [`log4j-core-test`](https://github.com/apache/logging-log4j2/pull/3061) (will be finished soon) | | 
| [`log4j-iostreams`](https://github.com/apache/logging-log4j2/pull/3248) (not merged) | | 

Am I correct in understanding that three modules require porting? (`log4j-osgi-test`, `log4j-core-test`, `log4j-iostreams`). Would you prefer to handle the porting directly, or would you like us to open the PRs against `main`?

Please note this PR https://github.com/apache/logging-log4j2/pull/3221 was related to the migration but not done by us. If I'm not mistaken this is not in `main` either. 

Thank you

**Comment by ppkarwasz** [comment]
> Am I correct in understanding that three modules require porting? (`log4j-osgi-test`, `log4j-core-test`, `log4j-iostreams`). Would you prefer to handle the porting directly, or would you like us to open the PRs against `main`?

There might be a lot of differences in `log4j-core-test` between `2.x` and `main`, so please make a separate PR for `main` if you can. `log4j-iostreams` shouldn't event be in `main` and I can port `log4j-osgi-test` myself.

> Please note this PR #3221 was related to the migration but not done by us. If I'm not mistaken this is not in `main` either.

Thanks for the remark, we didn't notice that, sorry. We'll double-check that PR to see if it contains independent work or is just a squash of all your PRs.

**Pull request merged**
