### PR TITLE
Fix MessageFactory support bug in SLF4JLoggerContext

### PR DESCRIPTION
**Pull request by vorburger**
Yo Log4j maintainers - hope this helps?

### CODE REVIEW

**Comment by vorburger** [comment]
Builds failing? I've opened https://issues.apache.org/jira/browse/LOG4J2-3229.

BTW should I be raising a 2nd PR to cherry-pick this to `release-2.x` from `master` where I'm submitting this one to, after it's LGTM & merge? Or does that happen automatically? Or do committers do this for PRs from contributors? Just asking to learn how you work in this community. (I'm an Apache committer on other projects.)

**Comment by garydgregory** [comment]
Hello @vorburger,

Please base your PR on the branch release-2.x.

**Comment by carterkozak** [comment]
It would be helpful to describe what has been resolved rather than using the description `fixed bug in ClassName` ;-)

I'd appreciate it if you could PR into `release-2.x` instead of `master`. The CI system works better on that branch, and it's what we release. I have an issue open with infra to change the default branch on this repo.

**Comment by vorburger** [comment]
> Please base your PR on the branch release-2.x.

done

> It would be helpful to describe what has been resolved rather than using the description `fixed bug in ClassName` ;-)

done

> I'd appreciate it if you could PR into `release-2.x` instead of `master`. The CI system works better on that branch, and it's what we release. I have an issue open with infra to change the default branch on this repo.

Good to know. Perhaps you would like to leave a related comment in https://issues.apache.org/jira/browse/LOG4J2-3229.

**Comment by vorburger** [comment]
BTW just FYI this PR is a result of my staring at this code in the context of [LOG4J2-3282](https://issues.apache.org/jira/browse/LOG4J2-3282) - it seemed like a Good Idea to fix this before copy/pasting this code into a new place... 😄

**Comment by carterkozak** [comment]
lgtm, thanks for the contribution! I'll get this merged once tests complete.

I've filed https://issues.apache.org/jira/browse/LOG4J2-3284 for tracking.

**Pull request merged**
