### PR TITLE
Pass params to log messages that expect params

### PR DESCRIPTION
**Pull request by travisspencer**
Fixed a couple log messages that were missing params.

### CODE REVIEW

**Comment by carterkozak** [comment]
Thanks for the contribution!

**Comment by travisspencer** [comment]
Thanks, @carterkozak , for accepting this fix. Do you know if I can get a build of this off the CI server somehow? I need the fix to test some other stuff, and I'm not able to compile the `master` branch. Seems it is failing on the CI server as well. Should I build from some other branch than master instead?

**Comment by carterkozak** [comment]
It works best if you target the release-2.x branch

**Comment by travisspencer** [comment]
Ah, good to know. Would it help at all if I cherry-pick it to that branch and make a separate PR or do commits to the main line get back-ported automatically somehow?

**Comment by carterkozak** [comment]
When I merge changes I cherry-pick them to the other branch, no need to create additional PRs since it tends to split the discussion. We add changelog entries for most contributions we review, so it doesn't take any extra time to cherry-pick at the same time :-)

**Comment by travisspencer** [comment]
Great. Thanks, @carterkozak .

**Pull request merged**
