### PR TITLE
[LOG4J2-2889] HtmlLayout support datePattern and timezone

### PR DESCRIPTION
**Pull request by gengyuanzhe**

### CODE REVIEW

**Review by jvz — APPROVED** [review]
LGTM. The factory method is kept due to backward compatibility here and removed in 3.x (the master branch).

**Comment by gengyuanzhe** [comment]
@jvz Thanks for reply. Is there anything else I need to do, or just wait for other members to review my code?

**Comment by jvz** [comment]
Nothing left for you as far as I can tell. We can see if anyone else wants to review before merging. I'm currently working on some build-related fixes/improvements before I merge this myself.

**Comment by gengyuanzhe** [comment]
Ok, I am not particularly familiar with the whole PR process, so I asked a lot of questions. Anyway, thank you for your patient repl.

**Pull request merged**
