### PR TITLE
LOG4J2-2091: Log4j respects the configured "log4j2.is.webapp" property

### PR DESCRIPTION
**Pull request by cakofony**
Some applications run embedded servlet containers sharing
a single logging context from the root application.

### CODE REVIEW

**Comment by jvz** [comment]
This PR looks good, though could you associate this with a JIRA ticket? Also, a unit test would be great to help avoid this bug from resurfacing in the future. Thanks!

**Comment by cakofony** [comment]
Hi @jvz, thanks for the quick reply!

I've added a jira ticket, but I'm not sure the best way to add real tests for this given how this is configured as static state. Any chance you could point me in the right direction?

**Comment by jvz** [comment]
I think you could add a simple test in log4j-web that asserts `Constants.IS_WEB_APP` if there isn't one already.

**Comment by cakofony** [comment]
Updated, thanks for the feedback!

**Comment by jvz** [comment]
Looks great, thanks! Anyone else on the team is welcome to merge this as I won't be around an appropriate computer until tomorrow at the earliest.

**Pull request closed without merging**
