### PR TITLE
Update KafkaManager.java

### PR DESCRIPTION
**Pull request by wuqian0808**
Avoid kafka thread leak during loggercontext reconfigure multiple times.

### CODE REVIEW

**Comment by wuqian0808** [comment]
Configure kafkaappender in log4j2.xml, then call below steps serveral times. The kafka thread will increase.         LoggerContext.getContext(false).reconfigure();
        LoggerContext.getContext(false).reconfigure();
        LoggerContext.getContext(false).reconfigure();

**Comment by gengyuanzhe** [comment]
In my opition, `org.apache.logging.log4j.kafka.appender.KafkaManager#releaseSub` should close the kafka producer when `reconfigure()`. The `close()` should not be invoked in`startup ()`, it is confused.

**Comment by wuqian0808** [comment]
> In my opition, `org.apache.logging.log4j.kafka.appender.KafkaManager#releaseSub` should close the kafka producer when `reconfigure()`. The `close()` should not be invoked in`startup()`, it is confused.

During reconfigure, LoggerContext will start new configuration and stop previous configuration. The firstime, prev is DefaultConfiguration, new configuration is eg: XmlConfiguration. Then the xml defined appender count in abstractmanager will be increased to 1. The nexttime reconfigure is called, xml defined appender count will be increased to 2. However the abstractmanager stop method will check if --count is <= 0. This cause the kafka producer thread never get stopped.

**Comment by wuqian0808** [comment]
> In my opition, `org.apache.logging.log4j.kafka.appender.KafkaManager#releaseSub` should close the kafka producer when `reconfigure()`. The `close()` should not be invoked in`startup()`, it is confused.

So each time loggercontext config start, the kafkamanager will create new kafka producer thread although it has one producer instance already. And the producer thread will never get closed.

**Comment by gengyuanzhe** [comment]
I tried your case, and you are right, the KafkaAppender do have the problem of thead leak. But **close when startup** is not the correct way  to solve this problem. Try to find why the **count in abstractmanager** increase each time when reconfigure(), fix it and make sure the kafkaManager close when prev.stop(). You'd better open an [issue](https://issues.apache.org/jira/browse/LOG4J2) to track this problem. And if you can provide unit test that failed without your PR, and success with your PR, it will help a lot to make this PR  accepted ASAP.

**Comment by wuqian0808** [comment]
> I tried your case, and you are right, the KafkaAppender do have the problem of thead leak. But **close when startup** is not the correct way to solve this problem. Try to find why the **count in abstractmanager** increase each time when reconfigure(), fix it and make sure the kafkaManager close when prev.stop(). You'd better open an [issue](https://issues.apache.org/jira/browse/LOG4J2) to track this problem. And if you can provide unit test that failed without your PR, and success with your PR, it will help a lot to make this PR accepted ASAP.

Sure. I will find a better way to fix this issue

**Comment by wuqian0808** [comment]
> I tried your case, and you are right, the KafkaAppender do have the problem of thead leak. But **close when startup** is not the correct way to solve this problem. Try to find why the **count in abstractmanager** increase each time when reconfigure(), fix it and make sure the kafkaManager close when prev.stop(). You'd better open an [issue](https://issues.apache.org/jira/browse/LOG4J2) to track this problem. And if you can provide unit test that failed without your PR, and success with your PR, it will help a lot to make this PR accepted ASAP.

The count is correct. It means the count of appenders using this manager. As we can see, the AbstarctManager will store a map of all static log4j2 managers. So during reconfigure, if managers is used by new config, the manager shouldn't be closed. Instead I just added a logic to check whether new kafka thread should be opended.

**Pull request closed without merging**
