### PR TITLE
Fix a typo in SLF4JServiceProvider

### PR DESCRIPTION
**Pull request by sander-adhese**

### CODE REVIEW

**Comment by ppkarwasz** [comment]
It's not a typo, it is the correct method name in SLF4J 1.8 (cf. [Javadoc](https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.8.0-beta4/org/slf4j/spi/SLF4JServiceProvider.html)).

Version 2.0 of SLF4J is developed in a separate module `log4j-slf4j20-impl` of [branch slf4j-2.0](https://github.com/apache/logging-log4j2/tree/slf4j-2.0) and will be merged with the default branch when SLF4J 2.0 is stable enough. Right now SLF4J 2.0 is still in its alpha phase.

**Comment by sander-adhese** [comment]
> It's not a typo, it is the correct method name in SLF4J 1.8 (cf. [Javadoc](https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.8.0-beta4/org/slf4j/spi/SLF4JServiceProvider.html)).
> 
> Version 2.0 of SLF4J is developed in a separate module `log4j-slf4j20-impl` of [branch slf4j-2.0](https://github.com/apache/logging-log4j2/tree/slf4j-2.0) and will be merged with the default branch when SLF4J 2.0 is stable enough. Right now SLF4J 2.0 is still in its alpha phase.

Thank you for the info! Regards

**Comment by krah034** [comment]
@ppkarwasz, SLF4J is now out of beta and was released as 2.0.0. See #1011

**Comment by ppkarwasz** [comment]
Thanks @krah034,

We have a [slf4j-2.0](https://github.com/apache/logging-log4j2/tree/slf4j-2.0) dedicated to the SLF4J 2.0 binding and I plan to merge it before the next release.

**Pull request closed without merging**
