### PR TITLE
LOG4J2-1192 (support dynamic Subject)

### PR DESCRIPTION
**Pull request by willdieh**
Edit sendMultipartMessage() to accept dynamic email Subject per comments made in ticket LOG4J2-1192 by Harry Bawls

### CODE REVIEW

**Comment by rgoers** [comment]
Please provide a unit test for this. Also, if you would like it in a Log4j 2.x release then please provide an equivalent patch on the release-2.x branch.

**Comment by rgoers** [comment]
Still waiting for a response .

**Comment by willdieh** [comment]
Yeah, sorry, I'm not even sure what kind of unit test this would need. Go ahead and close it if you need to, I've already implemented it in my own custom code.

**Comment by rgoers** [comment]
Closing at authors request

**Comment by zutnop** [comment]
It's a loss, that this wasn't merged into the project. I have been using it (for solving the related issue with dynamic subjects) for over 4 years in production with multiple projects. Works as expected.

**Pull request closed without merging**
