### PR TITLE
LOG4J2-2129 Added missing entries in module-info.java for Log4J API

### PR DESCRIPTION
**Pull request by bbucko**
This is only a quick fix for my sample project (https://github.com/bbucko/log4j2-jpms-sample).

### CODE REVIEW

**Comment by timofonic** [comment]
@bbucko @remkop @Vampire @mikaelstaldal @garydgregory @rgoers @mikaelstaldal 

What about this code? Any review or opinions about it? Any news?

**Comment by remkop** [comment]
Sorry, can you explain a bit more what this is about? What problem are you trying to solve?

**Comment by Vampire** [comment]
@timofonic what do I have to do with this?

**Comment by bbucko** [comment]
@remkop current version is not working with java 9. Two Service Providers were not defined/exported in module-info.java.

**Comment by remkop** [comment]
Can you be more specific? What is the error? Do you have a failing test or at least steps to reproduce? Why does the proposed change fix the problem?

**Comment by bbucko** [comment]
@remkop Sure, everything is described in [LOG4J2-2129](https://issues.apache.org/jira/browse/LOG4J2-2129). I've also prepared a sample project that fails when executed on java 9.

**Pull request merged**
