### PR TITLE
Fix for LOG4J2-2413

### PR DESCRIPTION
**Pull request by andresluuk**
A test and a fix for https://issues.apache.org/jira/browse/LOG4J2-2413

### CODE REVIEW

**Comment by garydgregory** [comment]
When I apply this patch on master, I get:
```
java.lang.AssertionError: There should be at least one row.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.logging.log4j.jdbc.appender.JdbcAppenderColumnMappingPatternTest.testDataSourceConfig(JdbcAppenderColumnMappingPatternTest.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.apache.logging.log4j.junit.LoggerContextRule$1.evaluate(LoggerContextRule.java:123)
	at org.apache.logging.log4j.jdbc.appender.JdbcRule$1.evaluate(JdbcRule.java:69)
	at org.apache.logging.log4j.junit.JndiRule$1.evaluate(JndiRule.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by andresluuk** [comment]
I removed an unused import, that should not affect the code.

The test itself is a copy past of the existing JdbcAppender tests and startup is exactly the same.
The main difference is that the config file name is different: log4j2-data-source-column-mapping-pattern.xml

I tryed with jdk 8 and jdk9 and it passed on my machine with both. Also the travis build passes. I presume it runs all the unit tests in there also?

The error in here is from the eclipse build. Maybe you could send the error from the command line run?  Maybe there is something different there. For example line number in JdbcAppenderColumnMappingPatternTest is different. Also what is your java version? When I tryed to compile log4j in my machine then it got some weird errors with jdk9 but jdk8 worked fine for the full build. 
Because the tests passes on my machine (with both JDK-s) and on travis and is similar to the existing tests I have currently no idea why it might fail on your machine, besides some environment difference in your machine.

**Comment by andresluuk** [comment]
Maybe you skiped compiling log4j-core when you ran it from the command line? Because the change to ColumnMapping is in the core module.

**Comment by andresluuk** [comment]
@garydgregory have you had the time to try a full clean build test on your machine? And if this fails then send me some more detailed loggs from the command line run. Then I would now why it fails on your machine.

**Comment by andresluuk** [comment]
Fix made in https://github.com/apache/logging-log4j2/commit/4613ba9fec04933cc73a351dfb2ed5fb6000ad27#diff-2acf44a35ca607f3b8e7378ec7823405 will close this one

**Pull request closed without merging**
