### PR TITLE
LOG4J2-1235 - org.apache.logging.log4j.core.appender.routing.IdlePurgePolicy not working correctly

### PR DESCRIPTION
**Pull request by aleksey-zvolinsky**
Made a change according to all provided comments in the ticket

### CODE REVIEW

**Comment by frendos** [comment]
Fixed conflicts with the base branch.
PR ready for review by Core Log4j team

**Comment by frendos** [comment]
@rgoers / @remkop  could you please review this pull request?

**Comment by remkop** [comment]
The patch looks good from a functionality point of view. Style-wise, in the Log4j community we agreed to put a space between the "if" and the opening bracket (see also the [style guide](https://logging.apache.org/log4j/2.x/javastyle.html)). Would you mind fixing that?

**Comment by frendos** [comment]
Added spaces after if and also replace few tabs with spaces

**Comment by garydgregory** [comment]
I cannot apply the patch cleanly to master. Would you mind adjusting it?

**Comment by frendos** [comment]
@garydgregory I just made rebase from apache/master. I think it should work for you now.

**Pull request closed without merging**
