### PR TITLE
Try to fix build on travis

### PR DESCRIPTION
**Pull request by PascalSchumacher**
I'm giving it another try (now that the scala api stuff was moved).

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
log4j-core-its fail to build because:

>logging.log4j:log4j-core-its:jar:2.9-SNAPSHOT: Could not find artifact org.apache.logging.log4j:log4j-server:jar:tests:2.9-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots)

No idea where log4j-server is hosted and where it is build, but its maven-jar-plugin configuration seems to be missing a `<goal>test-jar</goal>`.

**Comment by PascalSchumacher** [comment]
Now the log4j-server jar just needs to be build and published to the apache snapshot repository.

**Comment by timofonic** [comment]
@PascalSchumacher @remkop @Vampire @garydgregory @rgoers @mikaelstaldal
What happens with this? Any news?

 Maybe  @travis-CI developers like @nbrady-techempower @BanzaiMan @jake32321 @igorwwwwwwwwwwwwwwwwwwww  @joshk @sferic @ifesdjeen @randym @svenfuchs @roidrage @igorwwwwwwwwwwwwwwwwwwww @hahmed @BanzaiMan @drogus @joecorcoran @acnagy @janisozaur @edmorley @andyli @jimhester @cotsog @howlowck @mboudreau @meatballhat @lislis could help a bit to solve it.

Another alternative is switch to GitLab. They have their own CI tool and it seems quite resposive with Open Source projects 👍

**Comment by mboudreau** [comment]
@timofonic @PascalSchumacher a few things changed with the travis build since this was trialed.  Let me see what I can do tomorrow morning as I was about to go to bed.  Cheers.

**Comment by Vampire** [comment]
@timofonic STOP pinging me arbitrarily on random tickets. I just got a PR of mine merged and thus have the `Contributor` role. This is no reason to wildly ping me on unrelated issues. Please **stop** that blind mention-spamming!

**Comment by jvz** [comment]
Yes, please only ping members if anything, though we're all subscribed to notifications everywhere, so we all see these messages already. :)

As for CI usage, our main one is still Jenkins as it's the most supported one that ASF offers us (otherwise, as seen here, we're usually on our own in debugging problems). I don't remember why we have a Travis config in the first place.

**Pull request closed without merging**
