### PR TITLE
log4j-kafka added with "retryCount" function

### PR DESCRIPTION
**Pull request by joongs4**
I added log4j-kafka with "retryCount" function and also put test case.
The test case is setting up wrong kafka endpoint and retry count. And then check if history size is equal to retry count.

Thanks

I changed files below.

org.apache.logging.log4j.kafka.appender.KafkaManger
org.apache.logging.log4j.kafka.appender.KafkaAppender
org.apache.logging.log4j.kafka.appender.KafkaAppenderTest
KafkaAppenderTest.xml in log4j-core

### CODE REVIEW

**Comment by rgoers** [comment]
In the master branch the kafka support was moved to the log4j-kafka module.  We had not planned on moving it to its own module in 2.x.  It doesn't look like you moved it though but added a new module and left the old classes in place, so now there will be two instances of the KafkaAppender.

This just doesn't look right to me.

**Comment by joongs4** [comment]
Oh sorry, I removed log4j-kafka and modified below files in log4j-core projects

org.apache.logging.log4j.kafka.appender.KafkaManger
org.apache.logging.log4j.kafka.appender.KafkaAppender
org.apache.logging.log4j.kafka.appender.KafkaAppenderTest
KafkaAppenderTest.xml in log4j-core

**Comment by rgoers** [comment]
After applying the patch and fixing the typo in KafkaAppenderTest.xml the KafkaAppenderTest is failing with:

```[INFO] Running org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppenderTest
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.538 s <<< FAILURE! - in org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppenderTest
[ERROR] testAppendWithRetryCount(org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppenderTest)  Time elapsed: 0.021 s  <<< FAILURE!
java.lang.AssertionError: expected:<3> but was:<1>
	at org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppenderTest.testAppendWithRetryCount(KafkaAppenderTest.java:172)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KafkaAppenderTest.testAppendWithRetryCount:172 expected:<3> but was:<1>
[INFO] 
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by joongs4** [comment]
I fixted unit test and KafkaAppender.java

if exception occurs while sending Kafka, I put retry logic.
Thank you inadvance.

**Comment by joongs4** [comment]
Just check below files.

org.apache.logging.log4j.kafka.appender.KafkaAppender
org.apache.logging.log4j.kafka.appender.KafkaAppenderTest
KafkaAppenderTest.xml in log4j-core

**Comment by rgoers** [comment]
PR merged with minor changes.

**Pull request merged**
