### PR TITLE
[LOG4J2-1013][Lookups] Allow variables with dashes

### PR DESCRIPTION
**Pull request by fediazgon**
[JIRA Issue](https://issues.apache.org/jira/browse/LOG4J2-1013)

Move the logic of getting the default value from the StrSubstitutor to the Interpolator

### CODE REVIEW

**Comment by fdiazgon** [comment]
Hey @garydgregory @remkop. Could anyone check the status of this PR? It seems that Travis failed with an error not related to this code.

**Comment by remkop** [comment]
Can you rebase on master? This will also trigger another build.

**Comment by fdiazgon** [comment]
Done. Although I think I messed a little bit with the history.

**Comment by rgoers** [comment]
Closing this as a fix has been committed to allow keys with leading dashes to be escaped.

**Pull request closed without merging**
