### PR TITLE
Fixes travis build

### PR DESCRIPTION
**Pull request by ChristophKaser**
by skipping the install phase and using openjdk8

### CODE REVIEW

**Comment by jvz** [comment]
We need two JDKs available to compile right now (8 and 9+). Not sure if this would work.

**Comment by ChristophKaser** [comment]
For some reason, it did for me (see https://travis-ci.org/ChristophKaser/logging-log4j2/builds/637479679). I guess openjdk11 is installed by default.

**Comment by ChristophKaser** [comment]
That being said, it looks like the after_success script does not work. But I think this is an unrelated problem.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_c13123e.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_c13123e.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by jvz** [comment]
Oh that's great news! Let's see if this builds now.

**Comment by jvz** [comment]
Build passed. Thanks so much for figuring this out!

**Pull request merged**
