### PR TITLE
LOG4J-3215 Update the documentation instructions on using Log4j in a Gradle build

### PR DESCRIPTION
**Pull request by quapka**
See [Log4j 3215](https://issues.apache.org/jira/browse/LOG4J2-3215) for more details.

Please, have a look at the changes in `src/changes/changes.xml` I've failed to find out instructions on how to update this file properly :)

### CODE REVIEW

**Review by jamietanna — APPROVED** [review]

**Comment by vy** [comment]
Thanks so much @quapka! Applied your changes to both `release-2.x` and `master`.

**Comment by ppkarwasz** [comment]
This was closed automatically by Github because we renamed the `release-2.x` branch to `2.x`. Feel free to resubmit to the `2.x` branch.

**Comment by jamietanna** [comment]
Does it need reraising? It sounds like it may already be on those branches?

**Comment by ppkarwasz** [comment]
@jamietanna,

Sorry, I didn't notice that Volkan already merged it (without merging the PR).

**Comment by jamietanna** [comment]
No worries, appreciate you checking!

**Pull request closed without merging**
