### PR TITLE
Structured properties API enhancement proposal

### PR DESCRIPTION
**Pull request by jvz**
This PR has initial work toward implementing https://cwiki.apache.org/confluence/display/LOGGING/Properties+Enhancement with updates to the property parsing API. This is proposed to replace `PropertiesUtil` in general as the semantics for keys have changed.

### CODE REVIEW

**Comment by jvz** [comment]
Wow, CodeQL is a little paranoid there. Let me see what I can do about that.

**Review by rgoers — APPROVED** [review]
So far this looks good. I don't see any tie in between LoggerContext specific properties but that is OK for a first pass.

**Comment by jvz** [comment]
The `context` parameter in the new API is the main action for that. Properties of the form `log4j2.*.foo.bar` are filled in with the context name if specified (hence the unit test demos as migrating everything over to this API isn't done yet).

**Comment by jvz** [comment]
@ppkarwasz I've still got things to fix here, but the general shape of the changes are coming into place.

**Comment by jvz** [comment]
I'm going to begin working on breaking out the various entangled changes in this PR into independent changes. A partial list of things to extract to separate commits/PRs:

- [ ] Move `JsonReader` API to log4j-api in the `util` package
- [ ] Automatic spotless apply in build
- [ ] Replace `NullOutputStream` with `OutputStream::nullOutputStream`
- [ ] Remove `Serializable` from `Layout` API (we already tend to use custom interfaces to serializing to bytes)
- [ ] Remove `Serializable` from `LogEvent` API
- [ ] Update `Lazy::relaxed`
- [ ] Move `Recycler` API to log4j-api in `util`
- [ ] Move `AbstractLifeCycle` methods to default methods in `LifeCycle`
- [ ] Update `TriggeringPolicy` to extend `LifeCycle` (marked as a TODO from long ago)

**Comment by rgoers** [comment]
I am thrilled you are breaking out all the independent changes!

**Comment by jvz** [comment]
I hope you continue to remain thrilled when I submit the next PR as this one changes a bunch of files: LOG4J2-3228. We're removing `Serializable` from a few interfaces which lets us remove a bunch of serialization proxy classes (but not `ThrowableProxy` amusingly enough; that seems to be reused by JSON et al.).

**Pull request closed without merging**
