### PR TITLE
fix: fix NPE in PluginElementVisitor findNamedNode

### PR DESCRIPTION
**Pull request by azakordonets**
If "childType" is null, then the "if" block just get's skipped and on line 104 nullpointer will be called for `childType.getElement` command. 

This PR fixes the #1391 issue.

### CODE REVIEW

**Comment by jvz** [comment]
What do you think about the adjacent "FIXME" comment? Do you think this would fix that, too?

**Comment by vy** [comment]
@azakordonets, thanks so much for the report and the fix! I would appreciate it if you can next time also attach a `src/changelog/.2.x.x/<ticketId>_<description>.xml` entry along your PR.

@jvz, I don't think that FIXME is relevant any more. `visit()` contains `namedNode = findNamedNode(...); ...; return namedNode.getObject()`and its return value is checked against `null` at every call site.

**Comment by vy** [comment]
@azakordonets, if you have a test, I would be happy to merge that too. :heart_eyes:

**Comment by azakordonets** [comment]
Hey @vy , sorry for not including changes into the `changes` file and the test. I saw it in the template, but I have not done that in the past, so I was going to ask for help to whoever would review this. Two questions: 
1. How and in which format should I include changes to `src/changelog/.2.x.x/<ticketId>_<description>.xml` ? Any examples that I could use ? 
2. I wanted to write a test, but I could not find any tests related in that module and I was not sure whether it's on purpose or not. If not, then I will add those somewhere this week

**Comment by vy** [comment]
1. For changelog entry, just clone one of the XML files there. I already added one for you in bb0f38a50ffa12a86cef3db3096efa5351746357.
2. I had the impression you get this NPE from a particular configuration. If so, you can write a test that feeds this configuration and verify the successful bootstrap of the Log4j. (There are plenty of such tests in `log4j-core` for inspiration.)

**Pull request merged**
