### PR TITLE
make variableResolverPrefix/variableResolverSuffix/variableResolverEscape configable

### PR DESCRIPTION
**Pull request by qxo**
so that `logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n` will be ok
by change variableResolverPrefix/variableResolverSuffix to "$(" and ")"
ie:
```log4j2.properties
variableResolverPrefix=$(
variableResolverSuffix=)
appender.console.layout.pattern=$(logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n)
```

### CODE REVIEW

**Comment by rgoers** [comment]
What problem is this solving?  Is there a Jira issue?

**Comment by qxo** [comment]
> What problem is this solving? Is there a Jira issue?
```
${logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n} 
```
not work in the log4j2 config
After the PR, by change variableResolverPrefix/variableResolverSuffix  will fix my problem
ie:
```
variableResolverPrefix=$(
variableResolverSuffix=)
appender.console.layout.pattern=$(logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n)
```

**Comment by rgoers** [comment]
I still don't understand. Did you create a Lookup named logStdoutPattern? Where is the code for that? If not, what are you expecting the output to look like?

**Comment by qxo** [comment]
It's for log4j2 config file, such as log4j2.properties, log4j2.json or log4j.yaml
before this PR there no way for change variableResolverSuffix in config file
`${logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n}' 
will not work -- cause `variableResolverSuffix=}`

after this PR we can change variableResolverPrefix and  variableResolverSuffix to `$(` and `)`
then  logStdoutPattern with default value will work as below:
```
$(logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n)
```

**Comment by rgoers** [comment]
You are still not answering the question! Why is it necessary to change the suffix and prefix? what are you trying to do that doesn't work now?

**Comment by qxo** [comment]
Sorry for my poor english,  and I have no time ...
Please try add "appender.console.layout.pattern=${logStdoutPattern:-%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n}" to  log4j2.properties, you will see the issue!

suffix='}' will break the default value ( cause default value has '}')

**Comment by rgoers** [comment]
I understand what you are trying to do. However, this fix is unnecessary. You can solve the problem with this configuration:
```	
    <Properties>
        <Property name="defaultPattern">%d{yyyyMMdd HH:mm:ss} %-5p %c{20}:%L - %m%n</Property>
    </Properties>
    <Appenders>
	<List name="list">
	    <PatternLayout pattern="${logStdoutPattern:-${defaultPattern}}"/>
	</List>
    </Appenders>
```
In addition, you can use a PatternSelector to determine which Pattern to use.

**Comment by rgoers** [comment]
Closing this PR for the reasons stated in my prior comment.

**Pull request closed without merging**
