### PR TITLE
[LOG4J2-2211] Update StrSubstitutor.java

### PR DESCRIPTION
**Pull request by wangzhongkuo**
//fix bug LOG4J2-2211 (https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2211?filter=addedrecently)

### CODE REVIEW

**Comment by garydgregory** [comment]
Thank you for your patch. Can you please provide a unit test?

**Comment by wangzhongkuo** [comment]
i use the unit test org.apache.logging.log4j.core.lookup.MainInputArgumentsLookupTest

**Comment by garydgregory** [comment]
In general, this is the best process IMO:

1. Write a unit test that FAILS, therefore demonstrating that there is a problem.
2. Apply your bug fix
3. Run the test again and it now PASSES, demonstrating that your fix works.

**Comment by rgoers** [comment]
4. Run all the unit tests to make sure your fix didn't break something else.

**Comment by wangzhongkuo** [comment]
@garydgregory @rgoers

**Comment by wangzhongkuo** [comment]
@garydgregory @rgoers 
I'm glad you can pay attention to this problem and what's the final result? By the way, how long time difference exists between us, i'm in BeiJing...

**Comment by garydgregory** [comment]
Hello,
The fastest way to get traction on this issue is to provide a unit test in this PR.
Gary

**Comment by wangzhongkuo** [comment]
I have committed a new PR to the repository(pull 145) and i have run the first three steps, please check it.

**Comment by wangzhongkuo** [comment]
I'm disappointed

**Comment by garydgregory** [comment]
@wangzhongkuo: We are a volunteer-based organization, and as such, we look for as much help as we can as all of our schedules are busy, as is yours I imagine. This is why we ask for contributions and for contributors to ease the addition of new features and the inclusion of bug fixes by follow a fairly light process to minimize the impact of changes and of time in reviewing patches. 

With this in mind, this PR contains no unit tests, and as such will likely not get accepted (by me at least.) Do consider:

1. Write a unit test that FAILS, therefore demonstrating that there is a problem.
2. Apply your bug fix
3. Run the test again and it now PASSES, demonstrating that your fix works.
4. Run all the unit tests to make sure your fix didn't break something else.

Thank you,
Gary

**Comment by wangzhongkuo** [comment]
I did what you said in PR 145, but i don't known why all checks failed.

**Comment by garydgregory** [comment]
Failing unit tests is something you will have to resolve before we can consider accepting this patch. I, at least, do not have the time to look into this now.

**Comment by wangzhongkuo** [comment]
Is there any progress? @garydgregory

**Comment by rgoers** [comment]
Closing this PR. The issue was fixed a different way.

**Pull request closed without merging**
