### PR TITLE
workflow: add action to handle stale PRs

### PR DESCRIPTION
**Pull request by chenrui333**
It would be good to add some stale action to handle the stale PRs.

### CODE REVIEW

**Comment by rgoers** [comment]
I'm not sure I agree with this. It seems too simplistic. Sometimes PRs are good but we are slow to apply them.  Prior to every release I review all the PRs and close those I believe will never progress.

**Comment by chenrui333** [comment]
yeah, you can add some labels of having stale bot ignoring the `in progress` PRs.

**Comment by jvz** [comment]
I think the best stale not setting would be notifying PR authors when they have merge conflicts to fix the issue. I don't think we get enough PRs to worry about closing old ones; we tend to work in batches anyways.

**Comment by vy** [comment]
Thanks so much for letting us know of this feature, much appreciated @chenrui333! Please don't get demotivated by the questions from the rest of us. This is a part of the deal when you are contributing to a project. Looking forward to your future PRs!

I agree with the comments of @rgoers and @jvz. Log4j crew handles PRs in a rather unorthodox way given the scarcity of development resources, hence I take the liberty of closing this PR without merging it.

**Comment by garydgregory** [comment]
I agree with Ralph, staleness is not interesting here. The work I put in here very much sporadic so the age of a PR rarely matters,.what matters more are conflicts.

**Pull request closed without merging**
