### PR TITLE
Add tinylog benchmarks

### PR DESCRIPTION
**Pull request by pmwmedia**
Benchmarks for tinylog (https://github.com/pmwmedia/tinylog)

### CODE REVIEW

**Comment by garydgregory** [comment]
I do not see anything related to Log4j 2 on the Tinylog site. Is there?

**Comment by pmwmedia** [comment]
I have added tinylog as there are also benchmarks for Logback and JUL in your project. The comparisons are quite interesting.

There are also Log4j benchmarks in tinylog: https://github.com/pmwmedia/tinylog/tree/v1.2/benchmark

**Comment by remkop** [comment]
I'll take a look when I have time.

**Comment by mikaelstaldal** [comment]
Which JIRA issue is this?

**Comment by jvz** [comment]
Might need to add one. Should probably fall under a documentation bug type.

**Comment by rgoers** [comment]
I've looked at this but I am not sure I see the point.

**Comment by rgoers** [comment]
Closing. I don't see us adding this.

**Comment by ppkarwasz** [comment]
@pmwmedia, I started a [discussion on Github Discussions](https://github.com/apache/logging-log4j2/discussions/1972) regarding Tinylog 2.

I think we should not be afraid of adding Tinylog 2 to our benchmarks.

**Pull request closed without merging**
