### PR TITLE
LOG4J2-3204 Correct SpringLookup package name in Interpolator.

### PR DESCRIPTION
**Pull request by Francis-FY**
Correct SpringLookup package name in the constructor of Interpolator

### CODE REVIEW

**Comment by quaff** [comment]
This fix works. 
Before this commit `<Property name="app">${spring:spring.application.name:-unknown}</Property>` will always be `unknown` even `spring.application.name` present.

**Comment by quaff** [comment]
@rgoers , Please take a look at this.

**Comment by vy** [comment]
LGTM. Thanks so much for the contribution @Francis-FY!

**Comment by vy** [comment]
Cherry-picked to `master`.

**Pull request merged**
