### PR TITLE
trim levels read from properties file to remove trailing spaces

### PR DESCRIPTION
**Pull request by thuri**
trim levels after reading them from properties and before initializing any loggers.

If the level in a properties file contains a trailing space log4j2 won't initialize the logger correctly. In Effect the logger for whicht the level is defined will keep the inherited loglevel.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
I guess there should be a jira issue for this, so I created https://issues.apache.org/jira/browse/LOG4J2-1890

**Comment by thuri** [comment]
Du bist auch überall ;-) Danke für den Issue

Am 26. April 2017 19:49:52 MESZ schrieb Pascal Schumacher <notifications@github.com>:
>I guess there should be a jira issue for this, so I created
>https://issues.apache.org/jira/browse/LOG4J2-1890
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/logging-log4j2/pull/75#issuecomment-297489676

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by thuri** [comment]
Hi, so what can we do about the problem with the travis-ci build? Is there any chance this PR can be part of the next release?

**Comment by jvz** [comment]
No worries about the travis bit, something is broken there at the moment. The PR looks good, ready for merge, though I myself will not get a chance to do this for at least a few hours if anyone else wants to handle this right now. Thanks for the PR!

**Comment by thuri** [comment]
Any news on the PR?

**Comment by jvz** [comment]
Yikes, I totally forgot about this, sorry. This is ready to be merged.

**Comment by thuri** [comment]
Seems the PR is still not integrated. Can i help with something?

**Comment by garydgregory** [comment]
Thank you for you patch. It is now in Git master! :-) Keep them coming :-)

**Pull request closed without merging**
