### PR TITLE
[LOG4J2-3370] Initial SLF4J 2.0.x support

### PR DESCRIPTION
**Pull request by ppkarwasz**
Contains a basic `log4j-slf4j20-impl` module.

### CODE REVIEW

**Comment by yeikel** [comment]
Thank you for working on this

Do you have a release planned to include this?

**Comment by TWiStErRob** [comment]
@ppkarwasz any idea when the log4j-slf4j20-impl artifact will be available?

**Comment by ppkarwasz** [comment]
Hi @TWiStErRob,

We have snapshots of each commit merged into `release-2.x` on [https://repository.apache.org/snapshots]. Regarding the date official release, you should ask on the `log4j-user` mailing list.

**Comment by TWiStErRob** [comment]
Thank you! I opted in for snapshot for testing, so far looks good. Waiting on release, whenever it'll be.

**Comment by jvz** [comment]
We release once every few months usually at Ralph's convenience as he manages most releases. This usually involves looking through existing bug reports to clean up whatever can be done quickly, then preparing a release candidate which is still a somewhat time-consuming process, though not a huge deal.

**Pull request merged**
