### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by kinow**
Hello, found while updating a legacy project from log4j1 to log4j2, and reading the docs (which are great, by the way, a life saver. Thanks!)

### CODE REVIEW

**Comment by remkop** [comment]
Good catch, thanks!

**Comment by remkop** [comment]
Thanks for the pull request! This is now merged into master and the release-2.x branch.

Please verify and close the associated JIRA ticket: https://issues.apache.org/jira/browse/LOG4J2-2273

**Comment by kinow** [comment]
Thanks for merging it so quickly, and for creating the JIRA ticket. My next ticket will accompany a ticket :-)

**Comment by remkop** [comment]
You’re welcome!
If you really want to dot the i‘s and cross the t’s, prefix the commit message with the JIRA number. That’s the convention we use to keep our git history clean and easy to search. Thanks again for the contribution!

**Comment by kinow** [comment]
Roger thay. Exatly the same as OpenNLP. Will follow it if I find any other issues.

**Pull request merged**
