### PR TITLE
add configurable syslog layout

### PR DESCRIPTION
**Pull request by doumdoum**
Implements configurable syslog message as sketched in:
https://issues.apache.org/jira/browse/LOG4J2-969.

### CODE REVIEW

**Comment by garydgregory** [comment]
If the new layout implements a builder instead of a factory method, this will avoid deprecating the factory method in the future if anything needs to change in the layout. At least, that how I would do it.

**Comment by doumdoum** [comment]
OK on your remarks. 
I've simplified implementation: everything is done now in SyslogLayout.
A child Layout (such as PatternLayout) can be  specified, thus removing the need to specify layout properties in Factory.

**Comment by doumdoum** [comment]
ping ?

**Comment by cbarbaza** [comment]
Hi,

This feature is really important for me, what is the status of the pull request ?

Thanks.

**Comment by garydgregory** [comment]
Hi,

Does it apply cleanly on top of Git master now? Does a full build pass all tests?

Thank you,
Gary [away from PC]

**Comment by garydgregory** [comment]
@cbarbaza, @doumdoum,

Are you available to update this patch?

Gary

**Comment by rgoers** [comment]
LOG4J2-969 was closed. Is this patch still necessary?

**Comment by mikaelstaldal** [comment]
Can this PR be closed @garydgregory ?

**Comment by garydgregory** [comment]
Sure, since https://issues.apache.org/jira/browse/LOG4J2-969 is closed.

**Pull request closed without merging**
