### PR TITLE
(doc): Fix XML element names in javadoc

### PR DESCRIPTION
**Pull request by abuechler**

### CODE REVIEW

**Comment by abuechler** [comment]
https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/resources/Log4j-config.xsd#L190

**Comment by abuechler** [comment]
Build fails, because master is failing since 9th of July 2021 😞

**Comment by garydgregory** [comment]
@abuechler 
Please rebase on master.
TY

**Comment by abuechler** [comment]
@garydgregory 

I already [did](https://github.com/abuechler/logging-log4j2/commits/3f8822df8f2baf4a38cdd6bc27f9498deb1abe3b).

**Pull request merged**
