### PR TITLE
LOG4J2-2427 log4j2 filter for logs with no markers

### PR DESCRIPTION
**Pull request by rimal**
Related JIRA issue: https://issues.apache.org/jira/browse/LOG4J2-2427

### CODE REVIEW

**Comment by rgoers** [comment]
I was about to merge this but then realized I would have to write the documentation for it. Is it possible you could update the PR to add the documentation to the filters section?

**Comment by rimal** [comment]
@rgoers I have added the documentation. Now the check is giving a build error. Not sure why, because I have not changed any code. Not able to check on local as the build requires java 9 and now java 9 download is not available. Can you please help me out here.

**Comment by rimal** [comment]
> @rgoers I have added the documentation. Now the check is giving a build error. Not sure why, because I have not changed any code. Not able to check on local as the build requires java 9 and now java 9 download is not available. Can you please help me out here.

Merging with latest master resolved the issues. 
@rgoers Let me know if I need to make any other change in the PR.

**Comment by garydgregory** [comment]
Hi All,

I think NullFilterMarker would be a better class name.

Gary

**Comment by rgoers** [comment]
I have to disagree. NullFilterMarker sounds like it somehow is a marker that represents a null filter, whatever that is, whereas NoMarkerFilter clearly represents a filter for when no marker is present.

**Comment by carterkozak** [comment]
Agreed, I could see a case for `NullMarkerFilter` over `NullFilterMarker`, but I think the current name `NoMarkerFilter` makes the functionality very clear.

**Pull request merged**
