### PR TITLE
Add Link to Release History

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
It's a minor detail, but I didn't find any reference to the release history in the repository.

### CODE REVIEW

**Comment by larrywest42** [comment]
That's a helpful change, especially as the most recent version mentioned in "RELEASE-NOTE.md" is `2.11.0`, from 2018.

**Comment by vy** [comment]
@KristjanESPERANTO, thanks for the contribution! This update needs to go into `announcement.vm` in `release-2.x` branch.

**Comment by vy** [comment]
Hrm... I will do it myself. :+1:

**Comment by KristjanESPERANTO** [comment]
When will the changes be transferred from the `release-2.x` branch to the master branch?

The `RELEASE-NOTES.md` in the master branch is still outdated.

**Comment by vy** [comment]
> When will the changes be transferred from the release-2.x branch to the master branch?

[Never, since every release will have its own content.](https://lists.apache.org/thread/zrn7f1hz38x9q9vo8wmfbdb46w3wqtnm)

**Comment by KristjanESPERANTO** [comment]
Then you will never find a reference to the current release notes in the master branch. If that's the way you want it, I don't understand it, but that's okay too :slightly_smiling_face: 

Thank you very much for your patience and your work on log4j! 🎆

**Comment by vy** [comment]
I see your point @KristjanESPERANTO, maybe we should set the default branch to `release-2.x`. I guess this addresses your concern, right?

**Comment by KristjanESPERANTO** [comment]
Yes, that would address my point. The master branch is now the entry point for people who want to start dealing with the code. Since I can also see current changes this branch, it seems a bit inconsistent to find old release notes in there.

I have no idea about best practice, I'm just trying to give some feedback here :-)

**Pull request closed without merging**
