### PR TITLE
Marker examples should not use deprecate flow APIs

### PR DESCRIPTION
**Pull request by fabriziocucci**

### CODE REVIEW

**Comment by garydgregory** [comment]
Our base requirement is still Java 7. So we cannot just yet take this whole patch unless we split the examples into Java 7 and Java 8. I would like to take the changes for the entry APIs though.

**Comment by fabriziocucci** [comment]
@garydgregory sorry, I completely missed the requirements section:

> Log4j 2.4 and greater requires Java 7, versions 2.0-alpha1 to 2.3 required Java 6.

I will revert all Java 8 stuff and keep the entry API changes as you suggested.

Out of curiosity, is there any plan to ditch Java 7 support?

**Comment by fabriziocucci** [comment]
Done!

**Comment by jvz** [comment]
No real plan to upgrade to Java 8 for at least another year or so I believe. Too many people still depending on 7 as a baseline. It would be neat if there were some creative way to support multiple versions of Java similar to how Babel works for JS, though.

**Comment by garydgregory** [comment]
Fixed in Git master and tracked with https://issues.apache.org/jira/browse/LOG4J2-2029

**Comment by fabriziocucci** [comment]
I guess this one can be closed now!

**Pull request closed without merging**
