### PR TITLE
Exclude Eclipse project file from RAT in root POM

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
The [test failures here](https://github.com/vorburger/logging-log4j2/runs/4718590938?check_suite_focus=true) appears to be unrelated to this PR, looks like someone broke the build with a failing test in a recently merged change, @carterkozak @garydgregory @rgoers FYI:

```
org.apache.log4j.config.PropertiesConfigurationTest.testSystemProperties
Error:    Run 1: PropertiesConfigurationTest.testSystemProperties:138 expected:</tmp/[/]hadoop.log> but was:</tmp/[]hadoop.log>
Error:    Run 2: PropertiesConfigurationTest.testSystemProperties:138 expected:</tmp/[/]hadoop.log> but was:</tmp/[]hadoop.log>
Error:    Run 3: PropertiesConfigurationTest.testSystemProperties:138 expected:</tmp/[/]hadoop.log> but was:</tmp/[]hadoop.log>```

**Comment by garydgregory** [comment]
> The [test failures here](https://github.com/vorburger/logging-log4j2/runs/4718590938?check_suite_focus=true) appears to be unrelated to this PR, looks like someone broke the build with a failing test in a recently merged change, @carterkozak @garydgregory @rgoers FYI:
> 
> ```
> org.apache.log4j.config.PropertiesConfigurationTest.testSystemProperties
> Error:    Run 1: PropertiesConfigurationTest.testSystemProperties:138 expected:</tmp/[/]hadoop.log> but was:</tmp/[]hadoop.log>
> Error:    Run 2: PropertiesConfigurationTest.testSystemProperties:138 expected:</tmp/[/]hadoop.log> but was:</tmp/[]hadoop.log>
> Error:    Run 3: PropertiesConfigurationTest.testSystemProperties:138 expected:</tmp/[/]hadoop.log> but was:</tmp/[]hadoop.log>```
> ```
Hi,
Rebase on master and it should work. I initially wrote the test on macOS and later found it failed when I ran it on Windows.

**Comment by vorburger** [comment]
> Hi, Rebase on master and it should work. I initially wrote the test on macOS and later found it failed when I ran it on Windows.

But this is failing on the `release-2.x` branch, which presumably you want to "always build green", no? How about fixing this by merging #685?

**Comment by vorburger** [comment]
@garydgregory would you consider merging this PR, because the build test failure is obviously not related to the small change made to the POM here?

**Comment by garydgregory** [comment]
> @garydgregory would you consider merging this PR, because the build test failure is obviously not related to the small change made to the POM here?

Not yet.

The temp dir value is the example is "/tmp". Is this from your build or the CI build? I do not see such a value on macOS or Windows. The test assumes that the java io temp dir sys prop ends with a / but it seems that this is not the case here? If that is from the CI, then the test needs to use a DIFFERENT test specific sys prop to avoid this kind of issue. I can look at this in a few hours.

**Comment by vorburger** [comment]
> Not yet.

This PR is (only) about "Exclude Eclipse project file from RAT in root POM" (and #685 is about the test failure).

**Comment by garydgregory** [comment]
I'm not sure we need this: When I run `mvn apache-rat:check` in the root for the project for release-2.x, it passes, and I have Eclipse dot files all over the place. How are you seeing this failure?

**Comment by vorburger** [comment]
> Hi @vorburger I'm not sure we need this: When I run `mvn apache-rat:check` in the root for the project for release-2.x, it passes, and I have Eclipse dot files all over the place. How are you seeing this failure?

Agreed, this is not required. I encountered a RAT problem locally on `mvn verify` but it turned out that I had simply forgotten to add a new module to the `<modules>` in the root `pom.xml`.

**Comment by garydgregory** [comment]
@vorburger 
Thanks for the update 😀

**Pull request closed without merging**
