### PR TITLE
LOG4J2-1606, LOG4J2-2624 Add flag to disable automatic log4j shutdown in log4j-web

### PR DESCRIPTION
**Pull request by perry2of5**
Add context-param to prevent auto-shutdown of log4j in Servlet 3.0 environment. Add ServletContextListener to shutdown log4j which should probably be used as the first listener in an applications web.xml.

Also fully upgraded tests to JUnit 5 and removed use of deprecated test classes and deprecated test methods.

### CODE REVIEW

**Review by jvz — COMMENTED** [review]
Changes look pretty good to me! Looks like we have two more things to merge this:

1. Fill out and sign (can scan, e-sign, or gpg-sign) an [Apache ICLA](https://www.apache.org/licenses/icla.pdf) and send to the secretary as instructed there.
2. Add this flag to the documentation somewhere.

**Comment by perry2of5** [comment]
Matt, I submitted a signed Apache ICLA to the secretary. I am happy to work on updating the documentation. Tim

PS: Should we link the issues to this? Or is it too late since the pull request is already submitted?

**Comment by jvz** [comment]
Ok, I got the ICLA (I'm also the secretary coincidentally). You can link the issue to this, yes. You can update the title, too. We generally note issues in `src/changes/changes.xml` for the appropriate release the issue is resolved in, so you can add an entry corresponding to this issue in your PR if you'd like (otherwise I'll need to add it anyways).

**Comment by perry2of5** [comment]
How do I link the issues? Do I need to modify the PR in some way? Same question on updating src/changes/changes.xml. Thank you.

**Comment by jvz** [comment]
The changes.xml file is fairly self-explanatory, but you don't need to edit it. For linking this, you can just edit the title of the PR to include the LOG4J2 Jira issue id.

**Comment by perry2of5** [comment]
Thank you. I added "LOG4J2-1606, LOG4J2-2624" to the title but it doesn't seem to have linked to the JIRA issues. Perhaps there is a lag until a job runs. Let me know if I need to edit it.

**Comment by perry2of5** [comment]
Sorry...I didn't realize pushing to my fork would trigger any changes here. Obviously I'm not very familiar with github or working on this project. From the documentation it is clear this was going to happen. Sigh.

I don't think I changed anything other than prepending "LOG4J2-1606, LOG4J2-2624" to the commit message. I was trying to see who the autolinking of JIRA to GitHub would work. I'm not sure if I'm uncovering issues from other commits, if the tests are somewhat "flaky", or if I somehow broke something. I'll investigate tonight.

**Comment by perry2of5** [comment]
What developer name should I use in changes.xml? Do I need an official apache developer name? Should I just put in "jvz" to make things move along quickly?

**Comment by jvz** [comment]
In the changes, you can put `mattsicker` (my apache id), and add `due-to` with your name. That latter part is what gets generated as the "Thanks to Name" in the changelog (developer ids are separate).

**Comment by jvz** [comment]
As for auto-linking, that's handled by some ASF/GitHub bot that integrates things. If you see entries added to the Jira history of an issue, that's one area it links things.

**Comment by perry2of5** [comment]
I updated the changes.xml as you described squashed the update into the "add notes about LOG4J-2626..." commit and pushed to Github. I am not aware of any other tasks I need to perform. If there is anything for me to do, please let me know. 

Thank you for your help getting this ready.

**Comment by djohle** [comment]
@perry2of5 thank you very much for your contribution!
LOG4J2-1606 has been bugging me for almost a year now.  So glad I'll soon be able to remove my ugly workarounds.

**Comment by perry2of5** [comment]
You are very welcome. I was getting tired of telling junior staff not to use Spring's SmartLifecycle.stop() methods if they configured the web app entirely with XML. Now I can just update the application template to use this functionality and they can use whatever Spring features they want.

**Pull request merged**
