### PR TITLE
LOG4J2-3075 Fix formatting of nanoseconds in JsonTemplateLayout.

### PR DESCRIPTION
**Pull request by vy**

### CODE REVIEW

**Review by jvz — APPROVED** [review]
Nice use of TemporalAccessor to avoid garbage! Now that API makes a little more sense to me.

**Review by rgoers — APPROVED** [review]
I don't see anything concerning either. That said I didn't look at the Json Template Layout classes too much as I figure you know that way better than me.

**Comment by unclesam123** [comment]
Is this fix intended to improve also formatting of pattern type of formatting?

**Comment by vy** [comment]
> Is this fix intended to improve also pattern type of formatting?

No. This fix only fixes the issue for `JsonTemplateLayout`.

**Comment by unclesam123** [comment]
I have JsonTemplateLayout.json entry : 
  "@timestamp": {
    "$resolver": "timestamp",
      "pattern": {
      "format": "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'",
      "timeZone": "UTC"
    }
Still is formating without microseconds: 
"@timestamp":"2021-06-18T07:43:15.000000468Z"
means I wont have microseconds or I do something wrong with configuration?

**Comment by vy** [comment]
@unclesam123, this feature is aimed for 2.15.0, which is not released yet. Which version of `log4j-layout-template-json` are you using?

**Comment by unclesam123** [comment]
@vy I use 2.14.1 . Thanks for update. Will wait for 2.15.0 then.

**Comment by vy** [comment]
@unclesam123, you might also opt for using 2.5.0-SNAPSHOT temporarily until 2.5.0 is released.

**Comment by unclesam123** [comment]
Will check if I can't wait I will opt for snapshot. Thank you!

**Pull request merged**
