### PR TITLE
Add a new LuceneAppender which writes logging events to a lucene index library.

### PR DESCRIPTION
**Pull request by liyuj**
Add a new LuceneAppender which writes logging events to a lucene index library.The log4j2.xml configuration is as follows:
&lt;Lucene name="lucene" ignoreExceptions="true" target="/target/lucene/index" expiryTime=“1296000”&gt;
&lt;PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"/&gt;
&lt;IndexField name="time" pattern="%d{UNIX_MILLIS}" type="LongField"/&gt;
&lt;IndexField name="level" pattern="%-5level" /&gt;
&lt;IndexField name="content" pattern="%d{HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"/&gt;
&lt;/Lucene&gt;

this appender relies on the Lucene 5.5.4 version.
this patch adds the corresponding test cases.

### CODE REVIEW

**Comment by garydgregory** [comment]
I've created a new branch in our git repo called "Lucene5" based on your PR. There are some changes and fixes to allow the build to run. This WIP and not ready merge to master yet.

**Comment by mikaelstaldal** [comment]
Which JIRA issue is this?

**Comment by garydgregory** [comment]
Hi,

I can't recall if we have one but I brought in the code locally and started
fiddling with it.

Please see the Lucene 5 branch here:
https://git-wip-us.apache.org/repos/asf?p=logging-log4j2.git;a=shortlog;h=refs/heads/Lucene5

Gary

**Comment by garydgregory** [comment]
Note that the idea with the "5" naming is to have both modules log4j-lucene5 now and later log4j-lucene6

Gary

**Comment by liyuj** [comment]
This PR does not have a corresponding issue.
The code is used within our company and we think he has reusability, so it contributes to the community.
The functionality has been tested and no problem.

**Comment by garydgregory** [comment]
I created a branch called "lucene5" in git. Can you test this branch?

**Comment by garydgregory** [comment]
Can you provide any documentation for the new appender? That would help a LOT! :-)

**Comment by liyuj** [comment]
I can provide, but what does it contain? In what format?

**Comment by jvz** [comment]
You can add docs to the [appenders page](https://github.com/apache/logging-log4j2/blob/master/src/site/xdoc/manual/appenders.xml). The basic format is HTML currently. You can just follow the patterns established by all the other appenders in that page.

**Comment by liyuj** [comment]
https://www.zybuluo.com/liyuj/note/825932
I wrote a document. Can the community help me check?

**Comment by garydgregory** [comment]
Thank you for your submission @liyuj ! Can you try the "Lucene5" branch and confirm that it works for you?

**Comment by garydgregory** [comment]
Is what is happening
in org.apache.logging.log4j.lucene5.appender.LuceneAppender.stop(long,
TimeUnit) not good enough?

Gary

**Comment by liyuj** [comment]
committing each time is very affecting performance.
The practice now is to commit once per minute, commit too often, will lead to performance degradation, the submission interval is too long, will lead to the query can not be queried to the nearest log.
This time interval is dynamically adjustable,  we don't think it's very meaningful at the moment.

**Comment by liyuj** [comment]
What is the current state of this PR?
If want to continue, what do I need to do?

**Comment by jvz** [comment]
Updating your PR to be based on the latest master would be great. In the master branch, we've divided plugins into more modules now, so there's more examples as well.

**Pull request closed without merging**
