### PR TITLE
[LOG4J2-1559] Check proper value in LevelRangeFilter

### PR DESCRIPTION
**Pull request by andreyp1986**
https://issues.apache.org/jira/browse/LOG4J2-1559

### CODE REVIEW

**Comment by garydgregory** [comment]
Thank you for your report.
Can you also provide a unit test the demonstrates the problem? IOW, it should fail without your patch.

**Comment by andreyp1986** [comment]
NP, I'll add a test in org.apache.logging.log4j.core.filter.LevelRangeFilterTest.
Is it possible to somehow edit current pull request to add unit test commit?

**Comment by jvz** [comment]
If you want to keep it in a single commit, make your changes, then do `git commit --amend` and `git push --force`. There's also a way to do that using `git rebase -i`, but I find that overkill for this sort of thing.

**Comment by andreyp1986** [comment]
BTW, LevelRangeFilter default range values are wrong now.
```
        final Level actualMinLevel = minLevel == null ? Level.ERROR : minLevel;
        final Level actualMaxLevel = minLevel == null ? Level.ERROR : maxLevel;
```
According to log4j 1.2, default range is full range.
https://logging.apache.org/log4j/extras/apidocs/org/apache/log4j/filter/LevelRangeFilter.html
IE, better range should be OFF->ALL.

**Comment by andreyp1986** [comment]
Pushed a unit test.

**Pull request closed without merging**
