### PR TITLE
StrSubstitutor cannot parse nested braces

### PR DESCRIPTION
**Pull request by ngocnhan-tran1996**
As reported in:

[2679](https://github.com/apache/logging-log4j2/issues/2679)

### CODE REVIEW

**Comment by ppkarwasz** [comment]
@ngocnhan-tran1996,

Thank you for the PR.
Unfortunately this does not solve #2679, but just your particular problem with the `%d{...}` pattern converter as default value of a lookup.

IMHO `StrLookup` should be aware of the existence and syntax of pattern specifiers `%<something>{...}`, it should just count the number of `{` and `}`.
We also need to have a mechanism to insert a `}` as default value of a lookup.

**Comment by ngocnhan-tran1996** [comment]
@ppkarwasz 

I try to create class `ConverterKeysSubstitutor` for pattern specifiers ` %<something>{...}`. Please take a look and give me more test or some advice.

**Comment by ppkarwasz** [comment]
> IMHO `StrLookup` should be aware of the existence and syntax of pattern specifiers `%<something>{...}`, it should just count the number of `{` and `}`. We also need to have a mechanism to insert a `}` as default value of a lookup.

Ooops, I am really sorry, I meant "should not be aware".

**Comment by ngocnhan-tran1996** [comment]
@ppkarwasz 

I see, thanks for your help. I will close this PR

**Pull request closed without merging**
