### PR TITLE
[LOG4J2-2171] adding log4j2.forceTCLOnly option

### PR DESCRIPTION
**Pull request by rmannibucau**

### CODE REVIEW

**Comment by jvz** [comment]
Changes look pretty good. Could you rebase from master?

It would also be great if you could add a Jira issue for this so we can include this in the changelog. Thanks!

**Comment by rmannibucau** [comment]
@jvz  done :)

**Comment by jvz** [comment]
And could you re-add the docs? I just converted the page to asciidoc yesterday, so you'll have to check a different file: `src/site/asciidoc/manual/configuration.adoc`

**Comment by rmannibucau** [comment]
Oh missed that, done

**Comment by pgomulka** [comment]
@jvz @rmannibucau any reason why this wasn't merged into release-2.x? 
at the moment in 2.x `LoaderUtil#getClassloaders` does not take into account security manager and permission for `getClassLoader` (this fixes it)

**Comment by rmannibucau** [comment]
@pgomulka no reason, a lot of master should get released soon (like SPI improvements, this, probably https://github.com/apache/logging-log4j2/pull/473 too and so on) so mainly depends what are the releases plans of log4j I'd say.

**Pull request merged**
