### PR TITLE
LOG4J2-3060 LOG4J2-3185 Fix thread-safety issues in DefaultErrorHandler.

### PR DESCRIPTION
**Pull request by vy**
This change set supersedes #481 and #596.

### CODE REVIEW

**Comment by garydgregory** [comment]
Hi @vy 
I am curious as to why not simply make methods synchronized. Also, isn't it the case that you do not need to make variables volatile if they are updated inside a synchronized method or block?

**Comment by vy** [comment]
@garydgregory, thanks so much for the review. `volatile` modifiers are not needed indeed, removed them. I have used the `synchronized` block around the smallest possible group to minimize the wait duration under contention.

**Comment by mzbonnt** [comment]
> @garydgregory, thanks so much for the review. `volatile` modifiers are not needed indeed, removed them. I have used the `synchronized` block around the smallest possible group to minimize the wait duration under contention.

consider AtomicInteger or AtomicLong, which is more light weight than synchronized block

**Comment by garydgregory** [comment]
> > @garydgregory, thanks so much for the review. `volatile` modifiers are not needed indeed, removed them. I have used the `synchronized` block around the smallest possible group to minimize the wait duration under contention.
> 
> consider AtomicInteger or AtomicLong, which is more light weight than synchronized block

@mzbonnt You should look at the differences more carefully, considering multiple threads interweaving within these methods.

**Pull request merged**
