### PR TITLE
added retry count if failed to send

### PR DESCRIPTION
**Pull request by joongs4**
In my system, there is Kafka only for logging but as Kafka is not yet completely installed, it often crashes. If Kafka is down, an application gets blocked. I believe an application never gets affected by logging. Therefore, I added a attribute for retry count. 

I changed only two java files below.
- org.apache.logging.log4j.kafka.appender.KafkaManger
- org.apache.logging.log4j.kafka.appender.KafkaAppender

Thanks.

### CODE REVIEW

**Comment by rgoers** [comment]
sorry, this is showing 115 files changed. Did you modify line endings or something? I can't really review this as is.

**Comment by joongs4** [comment]
I modified and reopened

**Comment by rgoers** [comment]
This patch looks good to me. Can you also provide a patch to the release-2.x branch?  Also, is there any way a test can be provided to verify this?

**Comment by rgoers** [comment]
PR manually merged with minor changes.

**Pull request merged**
